### ISSUE TITLE
Update to V0.3 failure

### ISSUE THREAD

**Issue by wdey** [ACINQ/eclair#1024]
I try to update eclair from V02-beta9 to V0.3 on Windows 10; 
Bitcoin core is running 0.18.0
Java 8u211

OS: Windows 10 Pro
CPU: Intel Core i7-7600U 2.8 GHz 2.9 GHz
Memory: 20.0 GB

C:\Users\wdey\Downloads>java -jar eclair-node-gui-0.3-a5debcd.jar
Exception in thread "OkHttp Dispatcher" java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "iothread-2"
        at java.lang.StringCoding.decode(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at okio.Buffer.readString(Buffer.java:631)
        at okio.Buffer.readString(Buffer.java:614)
        at okio.RealBufferedSource.readString(RealBufferedSource.java:201)
        at com.softwaremill.sttp.okhttp.OkHttpBackend$$anon$2$$anonfun$6.apply(OkHttpBackend.scala:115)
        at com.softwaremill.sttp.okhttp.OkHttpBackend$$anon$2$$anonfun$6.apply(OkHttpBackend.scala:115)
        at scala.util.Try$.apply(Try.scala:192)
        at com.softwaremill.sttp.okhttp.OkHttpBackend$$anon$2.handleBasic(OkHttpBackend.scala:115)
        at com.softwaremill.sttp.ResponseAs$EagerResponseHandler$class.handle(ResponseAs.scala:63)
        at com.softwaremill.sttp.okhttp.OkHttpBackend$$anon$2.handle(OkHttpBackend.scala:106)
        at com.softwaremill.sttp.okhttp.OkHttpBackend.readResponse(OkHttpBackend.scala:91)
        at com.softwaremill.sttp.okhttp.OkHttpAsyncBackend$$anonfun$send$1$$anon$3.onResponse(OkHttpBackend.scala:212)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Uncaught error from thread [Uncaught error from thread [eclair-node-gui-akka.actor.default-dispatcher-5]: eclair-node-gui-akka.actor.default-dispatcher-11]: Java heap spaceJava heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[ for ActorSystem[eclair-node-gui]
java.lang.OutOfMemoryError: Java heap space
eclair-node-gui]
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
C:\Users\wdey\Downloads>dir

PS.
The failure to upgrade also completely screws the previous version, which also no more works.

**Comment by wdey** [comment]
I increased Java runtime parameter to 4GB : -Xmx4096m and now I am getting this error message:

C:\Users\wdey\Downloads>java -jar eclair-node-gui-0.3-a5debcd.jar
Uncaught error from thread [eclair-node-gui-akka.actor.default-dispatcher-7Uncaught error from thread [eclair-node-gui-akka.actor.default-dispatcher-15]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[
C:\Users\wdey\Downloads>

Any hint and/or recommendation would be appreciated !

**Comment by araspitzu** [comment]
Hi,

Are you able to reproduce the issue consistently even after system reboot? Is it possible that you had not enough resources  or other applications interfering with eclair?

**Comment by wdey** [comment]
Thanks for your feedback !
After upgrading Java to 11 (and modifying the environ variables for java and javac) it looks much better

C:\Users\wdey\Downloads>java -jar eclair-node-gui-0.3-a5debcd.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/C:/Users/wdey/Downloads/eclair-node-gui-0.3-a5debcd.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by araspitzu** [comment]
Glad it worked! We know about that warning and it's harmless, closing the issue.

**Comment by wdey** [comment]
Sorry, I have yet another issue! I did a final test, shuting down the server, and then rebooting;
What is the proper way, to start Eclair 0.3 properly.
In 0.2-beta9, I had a Eclair.exe file with a shortcut on desktop, C:\Users\wdey\AppData\Local\Eclair
I was under the wrong impression, that this exe file now points to a .3 version; however, the log files clearly say it starts 0.2-beta9.


2019-06-04 20:47:32,078 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2019-06-04 20:47:32,095 INFO  fr.acinq.eclair.Setup  - hello!
2019-06-04 20:47:32,096 INFO  fr.acinq.eclair.Setup  - **version=0.2-beta9** commit=eb0e45a8b127cb4d86580dfb649ac4c2b14e32a7
2019-06-04 20:47:32,097 INFO  fr.acinq.eclair.Setup  - datadir=C:\Users\wdey\.eclair
2019-06-04 20:47:32,219 INFO  o.b.Secp256k1Context  - couldn't find secp256k1 library, defaulting to spongycastle
2019-06-04 20:47:32,768 ERROR f.a.e.gui.FxPreloader  - java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)

**Comment by dpad85** [comment]
> What is the proper way, to start Eclair 0.3 properly.

Proper way is to run the `java -jar eclair-node-gui-0.3-a5debcd.jar` command.
You can find additional options [in the wiki](https://github.com/ACINQ/eclair/wiki/Run).

> In 0.2-beta9, I had a Eclair.exe file with a shortcut on desktop, C:\Users\wdey\AppData\Local\Eclair
I was under the wrong impression, that this exe file now points to a .3 version

> Has it to do, that the installation: java -jar xyz doesn't finish returning to the CMD prompt ??

This shortcut was created by the 0.2-beta9 installer, and points to the 0.2-beta9 installation folder that still exists on your computer (C:\Users\you_name\AppData\Local\Eclair). It is now obsolete.

If you want to have the same behaviour as this shortcut but with the 0.3 release, you can create a `.bat` file like this one:

```bat
start /B javaw -Declair.params... -jar C:\path\to\eclair-node-gui-0.3-2a89cf7.jar
```

**Comment by wdey** [comment]
Merci beaucoup !
