### ISSUE TITLE
Failed to load native library:secp256k1 [UnsatisfiedLinkError]

### ISSUE THREAD

**Issue by darwin** [ACINQ/eclair#1041]
My dockerized eclair node started failing since 31022ceca52e5e16e0353de3cdbb3c3330d2e574 (see the log bellow).

I don't see any changes in your Dockerfile. @sstone, any help what needs to be updated/fixed would be appreciated. Thanks.

```
+ exec java -Declair.chain=regtest -Declair.server.binding-ip=0.0.0.0 -Declair.server.port=9735 -Declair.api.enabled=true -Declair.api.port=8080 -Declair.api.password=devpass -Declair.api.binding-ip=0.0.0.0 -Declair.bitcoind.host=bitcoind1 -Declair.bitcoind.rpcport=18334 -Declair.bitcoind.rpcuser=devuser -Declair.bitcoind.rpcpassword=devpass -Declair.node-alias=bob -Declair.bitcoind.zmqblock=tcp://bitcoind1:28332 -Declair.bitcoind.zmqtx=tcp://bitcoind1:28333 -Declair.printToConsole=true -jar eclair-node.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/home/simnet/eclair-node.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by scala.reflect.package$ (file:/home/simnet/.capsule/apps/eclair-node-0.3.1-SNAPSHOT-notag/scala-library-2.11.12.jar) to method java.util.jar.JarFile$JarFileEntry.getName()
WARNING: Please consider reporting this to the maintainers of scala.reflect.package$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-06-17 19:09:54,749 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2019-06-17 19:09:55,151 INFO  fr.acinq.eclair.Setup  - hello!
2019-06-17 19:09:55,153 INFO  fr.acinq.eclair.Setup  - version=0.3.1-SNAPSHOT commit=notag
2019-06-17 19:09:55,154 INFO  fr.acinq.eclair.Setup  - datadir=/home/simnet/.eclair
2019-06-17 19:09:55,155 INFO  fr.acinq.eclair.Setup  - initializing secure random generator
Failed to load native library:secp256k1-a64a7708-94ba-42b5-add9-ac8ab7e3948d-libsecp256k1.so. osinfo: Linux/x86_64
java.lang.UnsatisfiedLinkError: /tmp/secp256k1-a64a7708-94ba-42b5-add9-ac8ab7e3948d-libsecp256k1.so (libgmp.so.10: cannot open shared object file: No such file or directory)
fatal error: org/bitcoin/Secp256k1Context.secp256k1_init_context()J
2019-06-17 19:09:55,296 ERROR fr.acinq.eclair.Boot$  - fatal error: org/bitcoin/Secp256k1Context.secp256k1_init_context()Jjava.lang.UnsatisfiedLinkError: org/bitcoin/Secp256k1Context.secp256k1_init_context()J
	at org.bitcoin.Secp256k1Context.<clinit>(Secp256k1Context.java:36)
	at fr.acinq.bitcoin.Crypto$.<init>(Crypto.scala:27)
	at fr.acinq.bitcoin.Crypto$.<clinit>(Crypto.scala)
	at fr.acinq.bitcoin.BlockHeader.hash$lzycompute(Block.scala:96)
	at fr.acinq.bitcoin.BlockHeader.hash(Block.scala:96)
	at fr.acinq.bitcoin.Block.hash$lzycompute(Block.scala:203)
	at fr.acinq.bitcoin.Block.hash(Block.scala:203)
	at fr.acinq.eclair.NodeParams$.makeChainHash(NodeParams.scala:120)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:92)
	at fr.acinq.eclair.Boot$.delayedEndpoint$fr$acinq$eclair$Boot$1(Boot.scala:39)
	at fr.acinq.eclair.Boot$delayedInit$body.apply(Boot.scala:30)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at fr.acinq.eclair.Boot$.main(Boot.scala:30)
	at fr.acinq.eclair.Boot.main(Boot.scala)
```

**Comment by sstone** [comment]
I cannot reproduce this with our latest docker build from  https://hub.docker.com/r/acinq/eclair.
Please provide more details: which docker image are you using ? Are use building it yoursefl ?

**Comment by darwin** [comment]
The Dockerfile was generated by [simverse](https://github.com/darwin/simverse) and I was building it myself from scratch without any caches involved (there should be a clean environment on Travis CI). The same issue was reproducible on my dev machine as well.

If you want to investigate it, here are the repro steps (should work at least on macOS or Ubuntu, I have just tested it under macOS 10.14):

```bash
> git clone https://github.com/darwin/simverse.git
> cd simverse
> ./sv create a1m2 # answer y to init repos
> ./sv enter
> ./dc build
> ./dc up
```

The generated docker-compose file is `_workspace/default/docker-compose.yml` and supporting files lying around, you might be interested in `_workspace/default/docker/eclair/Dockerfile`.

You should end up with output similar to this:
```
bob_1        | + exec java -Declair.chain=regtest -Declair.server.binding-ip=0.0.0.0 -Declair.server.port=9735 -Declair.api.enabled=true -Declair.api.port=8080 -Declair.api.password=devpass -Declair.api.binding-ip=0.0.0.0 -Declair.bitcoind.host=bitcoind1 -Declair.bitcoind.rpcport=18334 -Declair.bitcoind.rpcuser=devuser -Declair.bitcoind.rpcpassword=devpass -Declair.node-alias=bob -Declair.bitcoind.zmqblock=tcp://bitcoind1:28332 -Declair.bitcoind.zmqtx=tcp://bitcoind1:28333 -Declair.printToConsole=true -jar eclair-node.jar
alice_1      | + exec java -Declair.chain=regtest -Declair.server.binding-ip=0.0.0.0 -Declair.server.port=9735 -Declair.api.enabled=true -Declair.api.port=8080 -Declair.api.password=devpass -Declair.api.binding-ip=0.0.0.0 -Declair.bitcoind.host=bitcoind1 -Declair.bitcoind.rpcport=18334 -Declair.bitcoind.rpcuser=devuser -Declair.bitcoind.rpcpassword=devpass -Declair.node-alias=alice -Declair.bitcoind.zmqblock=tcp://bitcoind1:28332 -Declair.bitcoind.zmqtx=tcp://bitcoind1:28333 -Declair.printToConsole=true -jar eclair-node.jar
alice_1      | WARNING: An illegal reflective access operation has occurred
alice_1      | WARNING: Illegal reflective access by Capsule (file:/home/simnet/eclair-node.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
alice_1      | WARNING: Please consider reporting this to the maintainers of Capsule
alice_1      | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
alice_1      | WARNING: All illegal access operations will be denied in a future release
bob_1        | WARNING: An illegal reflective access operation has occurred
bob_1        | WARNING: Illegal reflective access by Capsule (file:/home/simnet/eclair-node.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
bob_1        | WARNING: Please consider reporting this to the maintainers of Capsule
bob_1        | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
bob_1        | WARNING: All illegal access operations will be denied in a future release
alice_1      | WARNING: An illegal reflective access operation has occurred
alice_1      | WARNING: Illegal reflective access by scala.reflect.package$ (file:/home/simnet/.capsule/apps/eclair-node-0.3.1-SNAPSHOT-notag/scala-library-2.11.12.jar) to method java.util.jar.JarFile$JarFileEntry.getName()
alice_1      | WARNING: Please consider reporting this to the maintainers of scala.reflect.package$
alice_1      | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
alice_1      | WARNING: All illegal access operations will be denied in a future release
bob_1        | WARNING: An illegal reflective access operation has occurred
bob_1        | WARNING: Illegal reflective access by scala.reflect.package$ (file:/home/simnet/.capsule/apps/eclair-node-0.3.1-SNAPSHOT-notag/scala-library-2.11.12.jar) to method java.util.jar.JarFile$JarFileEntry.getName()
bob_1        | WARNING: Please consider reporting this to the maintainers of scala.reflect.package$
bob_1        | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
bob_1        | WARNING: All illegal access operations will be denied in a future release
alice_1      | 2019-06-18 19:16:59,050 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
bob_1        | 2019-06-18 19:16:59,076 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
alice_1      | 2019-06-18 19:16:59,479 INFO  fr.acinq.eclair.Setup  - hello!
alice_1      | 2019-06-18 19:16:59,480 INFO  fr.acinq.eclair.Setup  - version=0.3.1-SNAPSHOT commit=notag
alice_1      | 2019-06-18 19:16:59,482 INFO  fr.acinq.eclair.Setup  - datadir=/home/simnet/.eclair
alice_1      | 2019-06-18 19:16:59,483 INFO  fr.acinq.eclair.Setup  - initializing secure random generator
bob_1        | 2019-06-18 19:16:59,493 INFO  fr.acinq.eclair.Setup  - hello!
bob_1        | 2019-06-18 19:16:59,495 INFO  fr.acinq.eclair.Setup  - version=0.3.1-SNAPSHOT commit=notag
bob_1        | 2019-06-18 19:16:59,498 INFO  fr.acinq.eclair.Setup  - datadir=/home/simnet/.eclair
bob_1        | 2019-06-18 19:16:59,500 INFO  fr.acinq.eclair.Setup  - initializing secure random generator
bob_1        | Failed to load native library:secp256k1-0b4a410a-febe-4ad7-9886-7bb2b380951a-libsecp256k1.so. osinfo: Linux/x86_64
bob_1        | java.lang.UnsatisfiedLinkError: /tmp/secp256k1-0b4a410a-febe-4ad7-9886-7bb2b380951a-libsecp256k1.so (libgmp.so.10: cannot open shared object file: No such file or directory)
alice_1      | Failed to load native library:secp256k1-17d6bff8-8008-4b5a-b2b0-5ec9f9b6835b-libsecp256k1.so. osinfo: Linux/x86_64
alice_1      | java.lang.UnsatisfiedLinkError: /tmp/secp256k1-17d6bff8-8008-4b5a-b2b0-5ec9f9b6835b-libsecp256k1.so (libgmp.so.10: cannot open shared object file: No such file or directory)
alice_1      | fatal error: org/bitcoin/Secp256k1Context.secp256k1_init_context()J
bob_1        | fatal error: org/bitcoin/Secp256k1Context.secp256k1_init_context()J
alice_1      | 2019-06-18 19:16:59,693 ERROR fr.acinq.eclair.Boot$  - fatal error: org/bitcoin/Secp256k1Context.secp256k1_init_context()Jjava.lang.UnsatisfiedLinkError: org/bitcoin/Secp256k1Context.secp256k1_init_context()J
alice_1      | 	at org.bitcoin.Secp256k1Context.<clinit>(Secp256k1Context.java:36)
alice_1      | 	at fr.acinq.bitcoin.Crypto$.<init>(Crypto.scala:27)
alice_1      | 	at fr.acinq.bitcoin.Crypto$.<clinit>(Crypto.scala)
alice_1      | 	at fr.acinq.bitcoin.BlockHeader.hash$lzycompute(Block.scala:96)
alice_1      | 	at fr.acinq.bitcoin.BlockHeader.hash(Block.scala:96)
alice_1      | 	at fr.acinq.bitcoin.Block.hash$lzycompute(Block.scala:203)
alice_1      | 	at fr.acinq.bitcoin.Block.hash(Block.scala:203)
alice_1      | 	at fr.acinq.eclair.NodeParams$.makeChainHash(NodeParams.scala:120)
alice_1      | 	at fr.acinq.eclair.Setup.<init>(Setup.scala:92)
alice_1      | 	at fr.acinq.eclair.Boot$.delayedEndpoint$fr$acinq$eclair$Boot$1(Boot.scala:39)
alice_1      | 	at fr.acinq.eclair.Boot$delayedInit$body.apply(Boot.scala:30)
alice_1      | 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
alice_1      | 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
alice_1      | 	at scala.App$$anonfun$main$1.apply(App.scala:76)
alice_1      | 	at scala.App$$anonfun$main$1.apply(App.scala:76)
alice_1      | 	at scala.collection.immutable.List.foreach(List.scala:392)
alice_1      | 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
alice_1      | 	at scala.App$class.main(App.scala:76)
alice_1      | 	at fr.acinq.eclair.Boot$.main(Boot.scala:30)
alice_1      | 	at fr.acinq.eclair.Boot.main(Boot.scala)
alice_1      |
bob_1        | 2019-06-18 19:16:59,693 ERROR fr.acinq.eclair.Boot$  - fatal error: org/bitcoin/Secp256k1Context.secp256k1_init_context()Jjava.lang.UnsatisfiedLinkError: org/bitcoin/Secp256k1Context.secp256k1_init_context()J
bob_1        | 	at org.bitcoin.Secp256k1Context.<clinit>(Secp256k1Context.java:36)
bob_1        | 	at fr.acinq.bitcoin.Crypto$.<init>(Crypto.scala:27)
bob_1        | 	at fr.acinq.bitcoin.Crypto$.<clinit>(Crypto.scala)
bob_1        | 	at fr.acinq.bitcoin.BlockHeader.hash$lzycompute(Block.scala:96)
bob_1        | 	at fr.acinq.bitcoin.BlockHeader.hash(Block.scala:96)
bob_1        | 	at fr.acinq.bitcoin.Block.hash$lzycompute(Block.scala:203)
bob_1        | 	at fr.acinq.bitcoin.Block.hash(Block.scala:203)
bob_1        | 	at fr.acinq.eclair.NodeParams$.makeChainHash(NodeParams.scala:120)
bob_1        | 	at fr.acinq.eclair.Setup.<init>(Setup.scala:92)
bob_1        | 	at fr.acinq.eclair.Boot$.delayedEndpoint$fr$acinq$eclair$Boot$1(Boot.scala:39)
bob_1        | 	at fr.acinq.eclair.Boot$delayedInit$body.apply(Boot.scala:30)
bob_1        | 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
bob_1        | 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
bob_1        | 	at scala.App$$anonfun$main$1.apply(App.scala:76)
bob_1        | 	at scala.App$$anonfun$main$1.apply(App.scala:76)
bob_1        | 	at scala.collection.immutable.List.foreach(List.scala:392)
bob_1        | 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
bob_1        | 	at scala.App$class.main(App.scala:76)
bob_1        | 	at fr.acinq.eclair.Boot$.main(Boot.scala:30)
bob_1        | 	at fr.acinq.eclair.Boot.main(Boot.scala)
bob_1        |
default_bob exited with code 1
default_alice exited with code 1
```

Thanks for your help.

**Comment by darwin** [comment]
I'm sorry for the noise. The problem was caused by outdated base image (openjdk for alpine linux).

I will have to find a better solution how to "merge" my common base image with evolving openjdk image.
