### ISSUE TITLE
Error: bitcoind must have wallet support enabled

### ISSUE THREAD

**Issue by AgXCz** [ACINQ/eclair#1322]
Hello.
I was trying to run LN node on Windows 10 according to some general tutorial, like: https://medium.com/@crypto_coffee/how-to-set-up-a-bitcoin-lightning-node-b54733fbcb7f
But from Eclair I got Error: bitcoind must have wallet support enabled. I was trying to solve it and at the end I found a root cause: It was because my data and wallet location was not that default. I used some alternative folder like c:\btc_core.  Bitcoin core itself worked well, but Eclair was not able to find my wallet probably. I think it is a bug. (or insufficient documentation as I was not able to find how to redirect Eclair to correct wallet).

Eclair will work as should.

Error: bitcoind must have wallet support enabled

I think it is reproducible quite easily.

latest, 0.3.3

Win10
AdoptOpenJDK 11.0.6.10 (x64)

Moving Bitcoin core to the default location helped. 

2020-02-16 00:48:26,201 INFO  a.e.slf4j.Slf4jLogger - Slf4jLogger started
2020-02-16 00:48:26,772 INFO  fr.acinq.eclair.Setup - hello!
2020-02-16 00:48:26,773 INFO  fr.acinq.eclair.Setup - version=0.3.3 commit=12ac1459e22f3bcea07b89bace7bf2516e00304e
2020-02-16 00:48:26,774 INFO  fr.acinq.eclair.Setup - datadir=C:\Users\AgX\.eclair
2020-02-16 00:48:26,774 INFO  fr.acinq.eclair.Setup - initializing secure random generator
2020-02-16 00:48:27,288 INFO  o.b.Secp256k1Context - secp256k1 library successfully loaded
2020-02-16 00:48:27,580 INFO  f.a.eclair.db.Databases$ - successful lock on eclair.sqlite
2020-02-16 00:48:27,925 INFO  fr.acinq.eclair.Setup - nodeid=03d6ad0506f03a80baead702a709b80a1100a61594d19ba0f7a0b34da1f95decfb alias=AgXEclair
2020-02-16 00:48:27,926 INFO  fr.acinq.eclair.Setup - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2020-02-16 00:48:28,781 ERROR f.a.e.gui.FxPreloader - fr.acinq.eclair.BitcoinWalletDisabledException$: bitcoind must have wallet support enabled
	at fr.acinq.eclair.BitcoinWalletDisabledException$.<clinit>(Setup.scala)
	at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
	at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2020-02-16 00:59:52,121 INFO  a.e.slf4j.Slf4jLogger - Slf4jLogger started
2020-02-16 00:59:52,733 INFO  fr.acinq.eclair.Setup - hello!
2020-02-16 00:59:52,734 INFO  fr.acinq.eclair.Setup - version=0.3.3 commit=12ac1459e22f3bcea07b89bace7bf2516e00304e
2020-02-16 00:59:52,736 INFO  fr.acinq.eclair.Setup - datadir=C:\Users\AgX\.eclair
2020-02-16 00:59:52,736 INFO  fr.acinq.eclair.Setup - initializing secure random generator
2020-02-16 00:59:52,991 INFO  o.b.Secp256k1Context - secp256k1 library successfully loaded
2020-02-16 00:59:56,630 ERROR f.a.eclair.db.Databases$ - could not create connection to sqlite databases: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
	at fr.acinq.eclair.db.sqlite.SqliteUtils$.obtainExclusiveLock(SqliteUtils.scala:98)
	at fr.acinq.eclair.db.Databases$.sqliteJDBC(Databases.scala:60)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:97)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:86)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-02-16 00:59:56,635 ERROR f.a.e.gui.FxPreloader - org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB._exec_utf8(Native Method)
	at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
	at fr.acinq.eclair.db.sqlite.SqliteUtils$.obtainExclusiveLock(SqliteUtils.scala:98)
	at fr.acinq.eclair.db.Databases$.sqliteJDBC(Databases.scala:60)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:97)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:86)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-02-16 01:00:12,899 INFO  a.e.slf4j.Slf4jLogger - Slf4jLogger started
2020-02-16 01:00:13,377 INFO  fr.acinq.eclair.Setup - hello!
2020-02-16 01:00:13,378 INFO  fr.acinq.eclair.Setup - version=0.3.3 commit=12ac1459e22f3bcea07b89bace7bf2516e00304e
2020-02-16 01:00:13,379 INFO  fr.acinq.eclair.Setup - datadir=C:\Users\AgX\.eclair
2020-02-16 01:00:13,379 INFO  fr.acinq.eclair.Setup - initializing secure random generator
2020-02-16 01:00:14,142 INFO  o.b.Secp256k1Context - secp256k1 library successfully loaded
2020-02-16 01:00:15,387 INFO  f.a.eclair.db.Databases$ - successful lock on eclair.sqlite
2020-02-16 01:00:15,667 INFO  fr.acinq.eclair.Setup - nodeid=03d6ad0506f03a80baead702a709b80a1100a61594d19ba0f7a0b34da1f95decfb alias=AgXEclair
2020-02-16 01:00:15,668 INFO  fr.acinq.eclair.Setup - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2020-02-16 01:00:16,377 ERROR f.a.e.gui.FxPreloader - fr.acinq.eclair.BitcoinWalletDisabledException$: bitcoind must have wallet support enabled
	at fr.acinq.eclair.BitcoinWalletDisabledException$.<clinit>(Setup.scala)
	at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
	at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2020-02-16 01:10:09,868 INFO  a.e.slf4j.Slf4jLogger - Slf4jLogger started
2020-02-16 01:10:10,521 INFO  fr.acinq.eclair.Setup - hello!
2020-02-16 01:10:10,522 INFO  fr.acinq.eclair.Setup - version=0.3.3 commit=12ac1459e22f3bcea07b89bace7bf2516e00304e
2020-02-16 01:10:10,522 INFO  fr.acinq.eclair.Setup - datadir=C:\Users\AgX\.eclair
2020-02-16 01:10:10,523 INFO  fr.acinq.eclair.Setup - initializing secure random generator
2020-02-16 01:10:11,043 INFO  o.b.Secp256k1Context - secp256k1 library successfully loaded
2020-02-16 01:10:11,225 INFO  f.a.eclair.db.Databases$ - successful lock on eclair.sqlite
2020-02-16 01:10:11,452 INFO  fr.acinq.eclair.Setup - nodeid=03d6ad0506f03a80baead702a709b80a1100a61594d19ba0f7a0b34da1f95decfb alias=AgXEclair
2020-02-16 01:10:11,452 INFO  fr.acinq.eclair.Setup - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2020-02-16 01:10:12,168 ERROR f.a.e.gui.FxPreloader - fr.acinq.eclair.BitcoinWalletDisabledException$: bitcoind must have wallet support enabled
	at fr.acinq.eclair.BitcoinWalletDisabledException$.<clinit>(Setup.scala)
	at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
	at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2020-02-16 09:00:10,545 INFO  a.e.slf4j.Slf4jLogger - Slf4jLogger started
2020-02-16 09:00:11,002 INFO  fr.acinq.eclair.Setup - hello!
2020-02-16 09:00:11,003 INFO  fr.acinq.eclair.Setup - version=0.3.3 commit=12ac1459e22f3bcea07b89bace7bf2516e00304e
2020-02-16 09:00:11,004 INFO  fr.acinq.eclair.Setup - datadir=C:\Users\AgX\.eclair
2020-02-16 09:00:11,005 INFO  fr.acinq.eclair.Setup - initializing secure random generator
2020-02-16 09:00:11,209 INFO  o.b.Secp256k1Context - secp256k1 library successfully loaded
2020-02-16 09:00:11,359 INFO  f.a.eclair.db.Databases$ - successful lock on eclair.sqlite
2020-02-16 09:00:11,569 INFO  fr.acinq.eclair.Setup - nodeid=03d6ad0506f03a80baead702a709b80a1100a61594d19ba0f7a0b34da1f95decfb alias=AgXEclair
2020-02-16 09:00:11,570 INFO  fr.acinq.eclair.Setup - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2020-02-16 09:00:12,290 WARN  f.a.e.b.f.FallbackFeeProvider - fr.acinq.eclair.blockchain.fee.SmoothFeeProvider@287264c4 failed, falling back to next fee providerjava.lang.RuntimeException: estimatesmartfee failed: Insufficient data or no feerate found
	at fr.acinq.eclair.blockchain.fee.BitcoinCoreFeeProvider$.parseFeeEstimate(BitcoinCoreFeeProvider.scala:77)
	at fr.acinq.eclair.blockchain.fee.BitcoinCoreFeeProvider$$anonfun$estimateSmartFee$1.apply(BitcoinCoreFeeProvider.scala:40)
	at fr.acinq.eclair.blockchain.fee.BitcoinCoreFeeProvider$$anonfun$estimateSmartFee$1.apply(BitcoinCoreFeeProvider.scala:40)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2020-02-16 09:00:12,890 INFO  fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(29834,6982,3000,3000,3000,3000,1000) feeratesPerKw=FeeratesPerKw(7458,1745,750,750,750,750,253)
2020-02-16 09:00:12,927 INFO  f.a.eclair.router.Router - loading network announcements from db...
2020-02-16 09:00:12,931 INFO  f.a.eclair.router.Router - loaded from db: channels=0 nodes=0
2020-02-16 09:00:12,960 INFO  f.a.eclair.router.Router - computing network stats...
2020-02-16 09:00:12,960 INFO  f.a.eclair.router.Router - initialization completed, ready to process messages
2020-02-16 09:00:13,036 INFO  fr.acinq.eclair.Setup - initial wallet address=3PYeGaSs9fxVpfw56uhNYHtpiELnQknSfz
2020-02-16 09:00:13,060 INFO  f.a.e.p.r.PostRestartHtlcCleaner - htlcsIn=0 notRelayed=0 relayedOut=0
2020-02-16 09:00:13,109 INFO  f.acinq.eclair.io.Server CON - bound on /0:0:0:0:0:0:0:0:9735
2020-02-16 09:00:14,063 INFO  f.a.e.b.b.zmq.ZMQActor - connected to tcp://127.0.0.1:29000
2020-02-16 09:00:14,069 INFO  f.a.e.b.b.zmq.ZMQActor - connected to tcp://127.0.0.1:29000
2020-02-16 09:00:14,074 INFO  fr.acinq.eclair.Boot$ - json API disabled
2020-02-16 09:10:12,298 WARN  f.a.e.b.f.FallbackFeeProvider - fr.acinq.eclair.blockchain.fee.SmoothFeeProvider@287264c4 failed, falling back to next fee providerjava.lang.RuntimeException: estimatesmartfee failed: Insufficient data or no feerate found
	at fr.acinq.eclair.blockchain.fee.BitcoinCoreFeeProvider$.parseFeeEstimate(BitcoinCoreFeeProvider.scala:77)
	at fr.acinq.eclair.blockchain.fee.BitcoinCoreFeeProvider$$anonfun$estimateSmartFee$1.apply(BitcoinCoreFeeProvider.scala:40)
	at fr.acinq.eclair.blockchain.fee.BitcoinCoreFeeProvider$$anonfun$estimateSmartFee$1.apply(BitcoinCoreFeeProvider.scala:40)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2020-02-16 09:10:12,681 INFO  fr.acinq.eclair.Setup - current feeratesPerKB=FeeratesPerKB(29834,6982,3000,3000,3000,3000,1000) feeratesPerKw=FeeratesPerKw(7458,1745,750,750,750,750,253)

eclair.conf:
eclair.chain=mainnet
eclair.node-alias=AgXEclair
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=some
eclair.bitcoind.rpcpassword=some
eclair.bitcoind.zmq="tcp://127.0.0.1:29000"
eclair.server.public-ips=[some]
eclair.node-color=49daaa

**Comment by t-bast** [comment]
I don't think that has anything to do with bitcoin's data location.
What version of Bitcoin Core are you using?
What's your `.bitcoin` configuration?
If you run `bitcoin-cli getbalance` in a terminal, what is the output?

**Comment by AgXCz** [comment]
Hello. Maybe it is Win10 specific. 
I moved it already to the default location (c:\Users\user\AppData\Roaming\Bitcoin\) and it started to work.
Previously it was like c:\btc_core and there was wallet.dat, blocks sub-folder, chainstate sub-folder etc.
Bitcoin core wallet was working fine, but Eclair reported that error.
I realized, that under default location that wallet.dat is in sub-folder "c:\Users\user\AppData\Roaming\Bitcoin\wallets\", but when custom location was specified, it was directly in c:\btc_core root.

There is my bitcoin.conf:
testnet=0
server=1
rpcuser=xxx
rpcpassword=yyy
txindex=1
rpcport=8332
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
addresstype=p2sh-segwit
deprecatedrpc=signrawtransaction
par=1


Wallet was working. I just uninstalled it, installed it back to the default location (also moved 300GB of data) and Eclair started to work flawlessly.

**Comment by t-bast** [comment]
Ok, let's close this issue then if it's resolved.
I think the location is a red herring TBH, we've had many people successfully run eclair with non-default locations. However when there was an issue, most of the time it was the bitcoin configuration that was bad (see https://github.com/ACINQ/eclair/issues/1263 for example).

**Comment by pm47** [comment]
FWIW, this really looks like bitcoind wasn't configured to use the alternate directory.
