### ISSUE TITLE
fatal error: bitcoind must have wallet support enabled when Bitcoin Core have multiple wallets

### ISSUE THREAD

**Issue by Sosthene00** [ACINQ/eclair#1330]
What behaviour did you expect?
Eclair should start up.

What was the actual behaviour (provide screenshots if the issue is GUI-related)?
When starting up eclair for the first time, eclair fails on startup with the following error message : fatal error: bitcoind must have wallet support enabled.

How reliably can you reproduce the issue, what are the steps to do so?
Just run `java -jar` with the .jar eclair file

What version of Eclair are you using, where did you get it (website, self-compiled, etc)?
Downloaded 3.3 version from here

What environment are you observing the error on (OS, JDK version)?
Linux Celeri 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Any extra information that might be useful in the debugging process.
The cause is that I have multiple wallets on Bitcoin Core, so every call needs `--rpcwallet=` option, which apparently eclair is not doing when it calls `getbalance`
I guess the best way to solve the problem would be to reorganise my wallets and only have the default one, but I wonder if there's a quick fix that would allow me to keep my wallets the way it is now.
Anyway I think this is a problem that should be taken care of at some point, at least by documenting the fact that it's not possible to run eclair with a multi wallets Bitcoin Core, or by modifying the way eclair makes its bitcoin-cli calls accordingly (maybe systematically add `--rpcwallet=` could work?).

eclair.log : 
2020-02-21 23:06:04,238 INFO  fr.acinq.eclair.Setup - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2020-02-21 23:06:06,056 ERROR fr.acinq.eclair.Boot$ - fatal error: bitcoind must have wallet support enabledfr.acinq.eclair.BitcoinWalletDisabledException$: bitcoind must have wallet support enabled
        at fr.acinq.eclair.BitcoinWalletDisabledException$.<clinit>(Setup.scala)
        at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
        at fr.acinq.eclair.Setup$$anonfun$10$$anonfun$apply$1.applyOrElse(Setup.scala:150)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Failure.recover(Try.scala:216)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by araspitzu** [comment]
Hello @Sosthene00 thanks for reporting the issue! You don't need to reorganize your wallets eclair will support multiple bitcoin wallets.
