### ISSUE TITLE
v0.4 upgrade to Akka 2.6 which I think broke Kamon monitoring

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#1410]
Getting this error:
```
2:20:28.254 [,] ERROR  fr.acinq.eclair.gui.FxPreloader - java.lang.ClassCastException: class akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory cannot be cast to class kamon.instrumentation.akka.instrumentations.DispatcherInfo$HasDispatcherName (akka.dispatch.ForkJoinExecutorConfigurator$ForkJoinExecutorServiceFactory and kamon.instrumentation.akka.instrumentations.DispatcherInfo$HasDispatcherName are in unnamed module of loader 'app')
	at kamon.instrumentation.akka.instrumentations.CopyDispatcherInfoToExecutorServiceFactory$.exit(DispatcherInstrumentation.scala:126)
	at akka.dispatch.ForkJoinExecutorConfigurator.createExecutorServiceFactory(ForkJoinExecutorConfigurator.scala:108)
	at akka.dispatch.Dispatcher.<init>(Dispatcher.scala:53)
	at akka.dispatch.DispatcherConfigurator.<init>(Dispatchers.scala:278)
	at akka.dispatch.Dispatchers.configuratorFrom(Dispatchers.scala:239)
	at akka.dispatch.Dispatchers.lookupConfigurator(Dispatchers.scala:154)
	at akka.dispatch.Dispatchers.lookup(Dispatchers.scala:120)
	at akka.dispatch.Dispatchers.<init>(Dispatchers.scala:107)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:964)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:283)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:327)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:271)
```
This is the fix
https://github.com/kamon-io/kamon-akka/commit/073c05cb22c8e6d97255f2ff63005847285c2665
So need version 2.0.1 - we are on 2.0.0

**Comment by n1bor** [comment]
https://github.com/kamon-io/kamon-akka/releases/tag/v2.0.1
Show this adds the 2.6 akka support.

**Comment by t-bast** [comment]
Good catch, I'll update this asap.
