### ISSUE TITLE
Locking configuration for postgres throws java.lang.NoSuchMethodError: java.time.Duration.toSeconds()

### ISSUE THREAD

**Issue by Christewart** [ACINQ/eclair#1506]
### stack trace

>2020-08-05 16:11:38,778 ERROR fr.acinq.eclair.Boot$ - fatal error: java.time.Duration.toSeconds()Jjava.lang.NoSuchMethodError: java.time.Duration.toSeconds()J
        at fr.acinq.eclair.db.Databases$.setupPgDatabases(Databases.scala:207)
        at fr.acinq.eclair.db.Databases$.init(Databases.scala:67)
        at fr.acinq.eclair.Setup.<init>(Setup.scala:98)
        at fr.acinq.eclair.Boot$.delayedEndpoint$fr$acinq$eclair$Boot$1(Boot.scala:43)
        at fr.acinq.eclair.Boot$delayedInit$body.apply(Boot.scala:34)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at fr.acinq.eclair.Boot$.main(Boot.scala:34)
        at fr.acinq.eclair.Boot.main(Boot.scala)

### java version
My understanding is that this is the supported java version

java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

Line of code causing the problem: 

https://github.com/ACINQ/eclair/blob/b63c4aa5a4c4cb0645d66517942d12151e6b2069/eclair-core/src/main/scala/fr/acinq/eclair/db/Databases.scala#L207

### locking config 
>eclair.db.postgres.lock-type = lease
eclair.db.postgres.lease.interval = 300 seconds
eclair.db.postgres.lease.renew-interval = 1 minute

**Comment by t-bast** [comment]
@rorp could you have a look?

**Comment by Christewart** [comment]
This was caused by the new startup script not using the java version I expected. I have java 8 and java 11 both installed on the machine, but for whatever reason java8 got chose by the script. Fixing this resolves this issue.
