### ISSUE TITLE
problem on performing Integration Test.

### ISSUE THREAD

**Issue by joemphilips** [ACINQ/eclair#156]
On Mac OS Sierra 10.12.6 

My command is.

```
mvn test -Dtest=IntegrationSpec 
```

And the output is.

```
14:57:19.264 INFO   - Slf4jLogger started
14:57:19.335 INFO   - using tmp dir: 
/path/to/my/workdir/eclair/eclair-core/target/integration-47f6913d-c5fb-44e4-8a23-c3adcd8c25f9
/path/to/my/workdir/eclair/eclair-core/target/bitcoin-0.14.0/bin/bitcoind: /path/to/my/workdir/eclair/eclair-core/target/bitcoin-0.14.0/bin/bitcoind: cannot execute binary file
14:57:20.005 INFO   - waiting for bitcoind to initialize...
14:57:50.040 INFO   - Slf4jLogger started
14:57:50.045 INFO   - hello!
14:57:50.046 INFO   - version=null commit=null
14:57:50.057 INFO   - initializing secure random generator
14:57:50.290 INFO   - generating fake channels
14:57:50.308 INFO   - stopping bitcoind
[ERROR] Tests run: 17, Failures: 7, Errors: 10, Skipped: 0, Time elapsed: 31.719 s <<< FAILURE! - in fr.acinq.eclair.integration.IntegrationSpec
[ERROR] wait bitcoind ready(fr.acinq.eclair.integration.IntegrationSpec)  Time elapsed: 30.047 s  <<< FAILURE!
java.lang.AssertionError: assertion failed: timeout 30 seconds expired: 
        at fr.acinq.eclair.integration.IntegrationSpec.withFixture(IntegrationSpec.scala:40)
        at fr.acinq.eclair.integration.IntegrationSpec.runTest(IntegrationSpec.scala:40)
        at fr.acinq.eclair.integration.IntegrationSpec.runTests(IntegrationSpec.scala:40)
        at fr.acinq.eclair.integration.IntegrationSpec.org$scalatest$FunSuiteLike$$super$run(IntegrationSpec.scala:40)
        at fr.acinq.eclair.integration.IntegrationSpec.org$scalatest$BeforeAndAfterAll$$super$run(IntegrationSpec.scala:40)
        at fr.acinq.eclair.integration.IntegrationSpec.run(IntegrationSpec.scala:40)
```

I tried to run `./target/bitcoin-0.14.0/bin/bitcoind` manually but it returns `zsh: exec format error: ./target/bitcoin-0.14.0/bin/bitcoind`

So I copied my system bitcoind (and `bitcoin-*` those are executable.) files in `./target/bitcoin-0.14.0/bin/bitcoind` and run again but having same error.
I realized that by insepcting `file` command system bitcoind returns

```
/usr/local/bin/bitcoind: Mach-O 64-bit executable x86_64
```

but `./target/bitcoin-0.14.0/bin/bitcoind` returns 

```
./target/bitcoin-0.14.0/bin/bitcoind: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=eb18d2bc1d03862fb8144e2dab8914641fc3175c, stripped
```

So I looked into `IntegrationSpec.scala` but couldn't understand how it prepares `bitcoind` executable. May be the problem is that my system bitcoind is version `0.15.99` but I still don't understand why it cannot create executable when testing.

What should I do to handle version difference? Or someone at least explain me how does eclair make a bitcoind executable in `target/` ?

thanks in advance.

**Comment by joemphilips** [comment]
Oh sorry, I think I understand.
Problem is that in `pom.xml` it downloads bitcoind binary but it only refers to windows and Linux executable.
I think I will send PR after enabling build in Mac
