### ISSUE TITLE
updaterelayfee API failing in v0.4.2

### ISSUE THREAD

**Issue by n1bor** [ACINQ/eclair#1570]
Looks like c.replyTo is not sent in Event(c: CMD_UPDATE_REALY_FEE...)?
Or is it failing to serialise to wire format the message?

Not really sure.

Am running on regtest with v0.4.2 my hash matches yours and all tests passed.

Thanks

```
12:46:45.904 [ n:0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2, c:facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458] INFO  akka://eclair-node-gui/user/$k/switchboard/peer-0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2/$b fr.acinq.eclair.channel.Channel - updating relay fees: prevFeeBaseMsat=1000 msat nextFeeBaseMsat=50000 msat prevFeeProportionalMillionths=100 nextFeeProportionalMillionths=25000
12:46:45.904 [ n:0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2, c:facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458] DEBUG akka://eclair-node-gui/user/$k/switchboard/peer-0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2/$b fr.acinq.eclair.channel.Channel - toRemoteSatoshis=Satoshi(100000) reserve=Satoshi(1000) aboveReserve=true for remoteCommitNumber=0
12:46:45.905 [ n:0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2, c:facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458] ERROR akka://eclair-node-gui/user/$k/switchboard/peer-0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2/$b fr.acinq.eclair.channel.Channel - null while processing msg=String in state=NORMAL
12:46:45.906 [ n:0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2, c:facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458] ERROR akka://eclair-node-gui/user/$k/switchboard/peer-0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2/$b fr.acinq.eclair.channel.Channel - msg=n/a stateData=DATA_NORMAL(Commitments(ChannelVersion(BitVector(32 bits, 0x00000001)),LocalParams(02f7636523f3696f43b15e7d1bc691568e0ebdde38783e40aa35a6f259573d8182,m/219572686'/1632229976/774954739/762158100/1579221970/676135440/1955838647/2108867582'/1',Satoshi(546),5000000000,Satoshi(1000),1 msat,CltvExpiryDelta(720),30,true,ByteVector(22 bytes, 0x0014a04d1ceb98664197ad312a88bd7191da75be0250),None,features=initial_routing_sync:optional,var_onion_optin:optional,gossip_queries:optional,option_support_large_channel:optional,gossip_queries_ex:optional,option_data_loss_protect:optional),RemoteParams(0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2,Satoshi(546),5000000000,Satoshi(1000),1 msat,CltvExpiryDelta(720),30,02c020dba50cdf6ff946e424ee71ad35f50ade7378808b786f0ee47a4e594aaff0,03cb462a5c9a9bee49d5f55ad5700a8b85926f20ec187272c312bede3590f25e29,020ea8cc9c22f970ca621a9a8ca7352c96fe052050ff97c28822230e21b02d3059,02b0c8a4969c027579bf2f9c96624eb90a64ff3401c84b40f78321b0abc704c2d8,03bc2cead0b66fef92ddfd924b9b82cfa926722d0a104ef2a6c1e7ef52736740ea,features=initial_routing_sync:optional,var_onion_optin:optional,gossip_queries:optional,option_support_large_channel:optional,gossip_queries_ex:optional,option_data_loss_protect:optional),1,LocalCommit(0,CommitmentSpec(Set(),FeeratePerKw(Satoshi(45000)),100000000 msat,0 msat),PublishableTxs(CommitTx(InputInfo(OutPoint(facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458,0),TxOut(Satoshi(100000),ByteVector(34 bytes, 0x0020899ad21bd4db1a693c9f97583271d3c978149e6bfa2f151f029e097beab28c58)),ByteVector(71 bytes, 0x522102c020dba50cdf6ff946e424ee71ad35f50ade7378808b786f0ee47a4e594aaff02102de9e949865cc1db0b585af6e82bb4aee89c7f71c833e8a2f009a2e30b6e1ca9852ae)),02000000000101facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b245800000000007b082180015c07010000000000220020f84e3bf932324d2b21440a93b00198294228e0ba12c29093639cb6f01e72c20f0400483045022100d96e9136e956ee8290e525ca56c79f3e075dbee8fbf4f1b7c973a53ff6091ed40220344efa3dfabdc3a64b54629609c304b68134d6c799912093b2b6c10d98bd50f401483045022100d2bcfefc6901b171f19ccbafc42dd51921f0ebb74d240915ec2a57691ebea80102200284a91f25cc557318831ccb716db83c1c6a5e8dcd3f5b0ec8ebbfe3e2bfac9b0147522102c020dba50cdf6ff946e424ee71ad35f50ade7378808b786f0ee47a4e594aaff02102de9e949865cc1db0b585af6e82bb4aee89c7f71c833e8a2f009a2e30b6e1ca9852aeb7755d20),List())),RemoteCommit(0,CommitmentSpec(Set(),FeeratePerKw(Satoshi(45000)),0 msat,100000000 msat),65198f9776c54d544df11d52552d9350691fb5041fb26d55463a49dd5302ee05,027d22164c957f8d84f10affcbb0d09b4ad45dedc1365bbe0ab8cfe46211ea0458),LocalChanges(List(),List(),List()),RemoteChanges(List(),List(),List()),0,0,Map(),Right(035b2085adcc675e2f440204233d0a61bf3e32d56923063bd6ad4598c7f6b75195),InputInfo(OutPoint(facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458,0),TxOut(Satoshi(100000),ByteVector(34 bytes, 0x0020899ad21bd4db1a693c9f97583271d3c978149e6bfa2f151f029e097beab28c58)),ByteVector(71 bytes, 0x522102c020dba50cdf6ff946e424ee71ad35f50ade7378808b786f0ee47a4e594aaff02102de9e949865cc1db0b585af6e82bb4aee89c7f71c833e8a2f009a2e30b6e1ca9852ae)),ShaChain(lastIndex = None),facf5373156a1cf2fd9b3658b4e3ca8aa7375e9722e1e687ab938b8c385b2458),1043x1x0,true,Some(ChannelAnnouncement(73eab898130068dffaf7d27dcfbd3078e00ed4994496c1a148a431f3a81ef4ea570383ef064586977ce29c765fa2d3ca86f138eeec7fb39c44e7a0e880512ef6,607c02786423d205c4ec7dfdfd8af0b5426864e495e385b588a60b9e389c086b2557dbdbbb34372863443c20299cfe77852e42bf8379ed75c0d0aa2114a795b7,46f8e49e1ec34712c0ea567a69cde8ff6dab2fb776fb100b301086a4cc1662e40a4e87c38f5ff9ee1dd2e7443c6af1db31025b2143276c81e48d226229c14afe,4c010ae30775b0543157dba401b181f11bc08b11bb4212cba6d1ab928dd24dfe3980e53e1ab22fd5a1b45ac073d4e6abc6eb32423995a90a85b61a9788c6d4a5,features=,06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f,1043x1x0,02f7636523f3696f43b15e7d1bc691568e0ebdde38783e40aa35a6f259573d8182,0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2,02de9e949865cc1db0b585af6e82bb4aee89c7f71c833e8a2f009a2e30b6e1ca98,02c020dba50cdf6ff946e424ee71ad35f50ade7378808b786f0ee47a4e594aaff0,ByteVector(empty))),ChannelUpdate(47a00d580e02a0e5c39993305ed933ed1eb5ef2d81be2cb3d71d62fb1f53ac2d785b9bc2ebd64b08f904a8bd689a257a31de1a23fa765089724cc93fd9af1f8a,06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f,1043x1x0,1603107372,1,0,CltvExpiryDelta(144),1 msat,1000 msat,100,Some(100000000 msat),ByteVector(empty)),None,None) java.lang.NullPointerException: null
	at fr.acinq.eclair.channel.Channel$$anonfun$9.applyOrElse(Channel.scala:950)
	at fr.acinq.eclair.channel.Channel$$anonfun$9.applyOrElse(Channel.scala:631)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at fr.acinq.eclair.channel.Channel$$anonfun$handleExceptions$1.applyOrElse(Channel.scala:2333)
	at fr.acinq.eclair.channel.Channel$$anonfun$handleExceptions$1.applyOrElse(Channel.scala:2330)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at akka.actor.FSM.processEvent(FSM.scala:804)
	at akka.actor.FSM.processEvent$(FSM.scala:801)
	at fr.acinq.eclair.channel.Channel.processEvent(Channel.scala:102)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:793)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)

12:46:45.916 [,] ERROR akka://eclair-node-gui/user/$k/switchboard/peer-0382aad2d3cfbdd44e61fdb73362c87ca4f94623776f8c8163f96aa8ec377880b2/$b akka.actor.OneForOneStrategy - nulljava.lang.NullPointerException: null
	at fr.acinq.eclair.wire.Error$.apply(LightningMessageTypes.scala:59)
	at fr.acinq.eclair.channel.Channel.handleLocalError(Channel.scala:2025)
	at fr.acinq.eclair.channel.Channel$$anonfun$handleExceptions$1.applyOrElse(Channel.scala:2335)
	at fr.acinq.eclair.channel.Channel$$anonfun$handleExceptions$1.applyOrElse(Channel.scala:2330)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at akka.actor.FSM.processEvent(FSM.scala:804)
	at akka.actor.FSM.processEvent$(FSM.scala:801)
	at fr.acinq.eclair.channel.Channel.processEvent(Channel.scala:102)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:793)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)

```

**Comment by t-bast** [comment]
Damn good catch...we'll patch that and make a bugfix release.

**Comment by t-bast** [comment]
We have update the 0.4.2 release to include the patch for this issue: https://github.com/ACINQ/eclair/releases/tag/v0.4.2
It should work correctly with this new version of the release.
