### ISSUE TITLE
"fetch latest block headers" test failure

### ISSUE THREAD

**Issue by ysangkok** [ACINQ/eclair#1628]
Using master from just now (c13ae5e), and running "mvn package" I get this test failure:

```
HeadersOverDnsSpec:
- init sqlite 2 times in a row
- fetch latest block headers *** FAILED ***
  java.lang.AssertionError: expected LatestHeaders(630450,HashSet(BlockHeaderAt(630450,BlockHeader(545259520,69ed618b1e0f87ce804e2624a34f507c13322c8f28b301000000000000000000,0e370896b5a57abf5426bc51e82a3fcb626a5af32c9eb8147fe9c513efbb1701,1589533219,387021369,2621689640)), BlockHeaderAt(630457,BlockHeader(536870912,28a1a12e1de0d77e1f58e1d90de97dd52aebcd0a8b5705000000000000000000,93669292cc29488c77d159fd5f153b66d689c0edaa284f556a587dc77585f442,1589540396,387021369,455558940)), BlockHeaderAt(630458,BlockHeader(536870912,ff4dc9eaac1ba97f16bd7287a2a05ecb4f2b013cfd640e000000000000000000,0a8ada0e68ebb19b68be274938df178a68de89031ff5bfc1c7612e82a83830b1,1589543047,387021369,1577264270)), BlockHeaderAt(630456,BlockHeader(536870912,b87220b7dd743fe4f1ee09d4fd4fd1d70608544ffaf001000000000000000000,9de701d6bd397e1be047ccc5fe30ff92f6d67bd71c526f9f67c1413c8a4c65cc,1589538896,387021369,3628975110)), BlockHeaderAt(630453,BlockHeader(536870912,db608b10a44b0b60b556f40775edcfb29d5f39eeeb7f0b000000000000000000,312b2dece5824b0cb3153a8ef7a06af70ae68fc2e45a694936cbbd609c747aa5,1589535335,387021369,2888738043)), BlockHeaderAt(630455,BlockHeader(536870912,4119a86146d81a66ac2670f5f36e0508d1312385f75d02000000000000000000,75871a6f838207ac1f55d201d5f4a306cb37e52b2be8006d7ac4cc3114ac6e9a,1589537466,387021369,2630321456)), BlockHeaderAt(630459,BlockHeader(536870912,30b5d50005fb4b56c1dbe12bc70e951779ab0d07e4ad02000000000000000000,a73e505c3943437b0fc732ee69bfda59b48c58709b4543c7b62af5134200684d,1589546987,387021369,876573765)), BlockHeaderAt(630454,BlockHeader(549453824,0951bd9340565493bc25101f4f7cbad1d094614ea8010e000000000000000000,fd0377e4c6753830fe345657921aface6159e41a57c09be4a6658ca9e2704ff0,1589536198,387021369,31796781)), BlockHeaderAt(630451,BlockHeader(1073733632,45367792598312e4cdbbf1caaeceafe38aef17eed8340d000000000000000000,47e447403a779461d013581137f66425c609fac6ed426bdba4f83a35f00786f3,1589533915,387021369,642913598)), BlockHeaderAt(630452,BlockHeader(536870912,0fce94e6ace8c26d3e9bb1fc7e9b85dc9c94ad51d8b00f000000000000000000,ca0a5ba5b2cdba07b8926809e4909278c392587e7c8362dd6bd2a6669affff32,1589534321,387021369,429900783))),bitcoinheaders.net), found LatestHeaders(630450,Set(),bitcoinheaders.net)
  at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:387)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:165)
  at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:144)
  at fr.acinq.eclair.blockchain.watchdogs.HeadersOverDnsSpec.$anonfun$new$1(HeadersOverDnsSpec.scala:48)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
```

**Comment by pm47** [comment]
Some tests which rely on external services have been causing trouble recently. They can be skipped by running 
 `mvn package -DtagsToExclude=external-api` (see https://github.com/ACINQ/eclair/commit/6330e76daf6c924d5e5b0ac031ed5ceaf88fbb2d).

**Comment by ysangkok** [comment]
All right, thanks for the quick reply. I guess I have a buggy DNS server... Since it is not strictly an Eclair issue, should I close this? Feel free to close it if you like.

**Comment by t-bast** [comment]
Yes, this is "by design".

If you do a simple `mvn test`, we will run some tests of external third-party APIs we depend on (some feerate providers, some chain explorers, headers over dns, etc). This ensures we're able to catch changes in our external dependencies and adapt quickly.

But these tests may fail randomly, because the third-party may be down or rate-limiting us.
That's why we added this `-DtagsToExclude=external-api` option, that skips over these tests.
If you want to test only `eclair`, that's what you should use (and it's what our CI uses).
