### ISSUE TITLE
Consequent API calls failed

### ISSUE THREAD

**Issue by engenegr** [ACINQ/eclair#1855]
I've used some Python script from which I did API requests to Eclair node. I needed generating new invoices.

In every second consequent calls I got such error. After second call, if i tried to request node it returned expected result (with invoice) or error (if request is malformed).

```
2021-06-30 16:51:20,377 ERROR f.a.eclair.Boot - API call failed with cause=Substream Source(EntitySource) cannot be materialized more than oncejava.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once
	at akka.stream.impl.fusing.SubSource$$anon$13.createMaterializedTwiceException(StreamOfStreams.scala:828)
	at akka.stream.impl.fusing.SubSource$$anon$13.<init>(StreamOfStreams.scala:799)
	at akka.stream.impl.fusing.SubSource.createLogic(StreamOfStreams.scala:795)
	at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:106)
	at akka.stream.stage.GraphStageWithMaterializedValue.createLogicAndMaterializedValue(GraphStage.scala:50)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:699)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:498)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:741)
	at akka.stream.scaladsl.Source.runWith(Source.scala:118)
	at akka.http.scaladsl.model.HttpEntity.toStrict(HttpEntity.scala:94)
	at akka.http.scaladsl.model.HttpEntity.toStrict$(HttpEntity.scala:88)
	at akka.http.scaladsl.model.HttpEntity$Default.toStrict(HttpEntity.scala:384)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$toStrictEntity$3(BasicDirectives.scala:400)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:50)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
```

**Comment by t-bast** [comment]
@pm47 @sstone this looks similar to what joost observed with their performance benchmark (configuration of our akka http API layer)?

**Comment by sstone** [comment]
joost had an issue with invoice generation failing sometimes but I don't remember this specific error.

@engenegr which version of eclair are you using ? can you reproduce the problem with `eclair-cli` ? are there other errors or warnings in your logs ?

**Comment by engenegr** [comment]
@sstone `0.5.2-SNAPSHOT-898c17b`.

I couldn't reproduce the same error by calling `eclair-cli` which works similar way.

Tried to reproduce this error just now and I just can't get the same result anymore (failure). My Python code works and produces invoices.

**Comment by engenegr** [comment]
This error occurred 3 times in total
```
2021-06-30 16:44:59,866 ERROR f.a.eclair.Boot - API call failed with cause=Substream Source(EntitySource) cannot be materialized more than oncejava.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once
2021-06-30 16:49:19,125 ERROR f.a.eclair.Boot - API call failed with cause=Substream Source(EntitySource) cannot be materialized more than oncejava.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once
2021-06-30 16:51:20,377 ERROR f.a.eclair.Boot - API call failed with cause=Substream Source(EntitySource) cannot be materialized more than oncejava.lang.IllegalStateException: Substream Source(EntitySource) cannot be materialized more than once
```

**Comment by t-bast** [comment]
This looks related to https://github.com/akka/akka-http/issues/745#issuecomment-271571342, however we already wrap our `get` and `post` inside a `toStrictEntity`. I tried wrapping at a higher layer in https://github.com/ACINQ/eclair/pull/1884 in case this happens when parsing the headers, but I'm really unsure this is the right fix. @engenegr can you test this branch and let me know if it fixes the issue on your machine?

![no idea](https://user-images.githubusercontent.com/31281497/125974324-85fe49f7-9816-49db-b60c-066983967724.jpg)

**Comment by engenegr** [comment]
I will try to test it and report.

**Comment by t-bast** [comment]
Be careful though, a small warning here: we've made DB migrations since the last eclair version. That means that once you run the new code, you cannot go back to the older code as the DB schemas will be incompatible, so maybe you should test this version on a testnet node, definitely not your mainnet one.

**Comment by engenegr** [comment]
I'm aware of that, actually I've upgraded mainnet node. I will try to reproduce error on the testnet.

**Comment by t-bast** [comment]
Ok, it shouldn't be a big issue though as long as you just make sure you install newer versions next, not older ones.

**Comment by engenegr** [comment]
Hey @t-bast I'm running into issues on my testnet node and it looks like eclair api doesn't even start.

```
ERROR akka.dispatch.Dispatcher - You are using version 10.2.4 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.4 of the [akka-http] artifacts to your project. Here's a complete collection of detected artifacts: (10.2.0, [akka-http]), (10.2.4, [akka-http-core, akka-parsing]). See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowedjava.lang.IllegalStateException: You are using version 10.2.4 of Akka HTTP, but it appears you (perhaps indirectly) also depend on older versions of related artifacts. You can solve this by adding an explicit dependency on version 10.2.4 of the [akka-http] artifacts to your project. Here's a complete collection of detected artifacts: (10.2.0, [akka-http]), (10.2.4, [akka-http-core, akka-parsing]). See also: https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed
```
I tried to investigate it and supposed that one my plugin is outdated, re-compiled it, then even disabled it completely but this error persists.

It is for latest release. I did `mvn clean` before build.

**Comment by t-bast** [comment]
This should have been fixed by https://github.com/ACINQ/eclair/pull/1889, I'll rebase my branch on top of `master`

**Comment by t-bast** [comment]
I have rebased https://github.com/ACINQ/eclair/pull/1884 on top of the 0.6.1 release, can you try with that updated version?

**Comment by engenegr** [comment]
@t-bast it works now. Thanks.

**Comment by engenegr** [comment]
@t-bast report.

I've built custom Python script reproducing basically similar requests to Eclair node and set it up with various sleeping times between consequent requests. The shortest interval I've tested is `pause = 0.001 #second` and Eclair didn't show any error related to this issue.

Thus, I'm closing it. Thank you for your work.
