### ISSUE TITLE
Substream Source(EntitySource) cannot be materialized more than once

### ISSUE THREAD

**Issue by pvyhnal-generalbytes** [ACINQ/eclair#1940]
Calling getsentinfo, parseinvoice API calls returns "Substream Source(EntitySource) cannot be materialized more than once" error very often (maybe 90% chance of getting this error)

Eclair v0.6.1 from github, Ubuntu

2 years ago we used to have a workaround (possibly for https://github.com/ACINQ/eclair/pull/1032) to retry 3 times if we got "Substream Source cannot be materialized more than once" and it was working.
Now after updating eclair the error is slightly different but happen so often that it makes eclair unusable in our case.

**Comment by t-bast** [comment]
Duplicated of #1855.
This is fixed on `master` already.

**Comment by generalbytes** [comment]
Just adding full exception.

2021-09-06 16:28:32,073 ERROR f.a.eclair.Boot - API call failed with cause=Substream Source(EntitySource) cannot be materialized more than oncejava.lang.IllegalStateException: Substream Source(EntitySource) c
annot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$11.createMaterializedTwiceException(StreamOfStreams.scala:843)
        at akka.stream.impl.fusing.SubSource$$anon$11.<init>(StreamOfStreams.scala:813)
        at akka.stream.impl.fusing.SubSource.createLogic(StreamOfStreams.scala:809)
        at akka.stream.stage.GraphStage.createLogicAndMaterializedValue(GraphStage.scala:106)
        at akka.stream.stage.GraphStageWithMaterializedValue.createLogicAndMaterializedValue(GraphStage.scala:50)
        at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:705)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:503)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:452)
        at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:444)
        at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:746)
        at akka.stream.scaladsl.Source.runWith(Source.scala:118)
        at akka.http.scaladsl.model.HttpEntity.toStrict(HttpEntity.scala:94)
        at akka.http.scaladsl.model.HttpEntity.toStrict$(HttpEntity.scala:88)
        at akka.http.scaladsl.model.HttpEntity$Default.toStrict(HttpEntity.scala:384)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$toStrictEntity$3(BasicDirectives.scala:400)
        at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
        at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:50)
:
