### ISSUE TITLE
Trying to execute eclair-node_2.11-0.2-SNAPSHOT-6d7717c-capsule-fat.jar throws an error in Ubuntu 16.10 - KDE Plasma

### ISSUE THREAD

**Issue by fjrojasgarcia** [ACINQ/eclair#21]
Trying to execute eclair-node_2.11-0.2-SNAPSHOT-6d7717c-capsule-fat.jar throws an error in Ubuntu 16.10 - KDE Plasma after "mvn package -DskipTests" build OK even in Travis-ci;

java -jar eclair-node_2.11-0.2-SNAPSHOT-6d7717c-capsule-fat.jar
cassini 2016-11-13 00:31:08,358 INFO  fr.acinq.eclair.Setup  - hello!
cassini 2016-11-13 00:31:18,225 INFO  fr.acinq.eclair.Setup  - nodeid=03befb4f8ad1d87d4c41acbb316791fe157f305caf2123c848f448975aaf85c1bb
cassini 2016-11-13 00:31:20,856 INFO  akka.event.slf4j.Slf4jLogger  - Slf4jLogger started
cassini 2016-11-13 00:31:23,640 ERROR fr.acinq.eclair.gui.FxApp  - Something wrong happened: akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/json
	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:155)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:111)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:108)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$16$$anonfun$apply$17.apply(Unmarshaller.scala:88)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$16$$anonfun$apply$17.apply(Unmarshaller.scala:88)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)

**Comment by sstone** [comment]
Hi,
We cannot reproduce this problem on Ubuntu 16.10 (standard, with Unity and not KDE). We use git commit ids as part of our packaged jar's filename and I cannot find a commit that starts with 6d7717c which repo did you use ?  Can you please try with our master branch at 3fc25da4616153ab3339660b8c36f0b5bddba304 ? 
Thank you

**Comment by fjrojasgarcia** [comment]
Hi, 
6d7717c is the id of a commit on my fork.

That commit basically solves -error File name too long- running over ecryptfs" adding -Xmax-classfile-name arg to maven-scala-plugin.

My commit is in;
https://github.com/fjrojasgarcia/eclair/commit/64c656c75e1b8c461d493dfc340845b0903a1405

Without that commit I can not build over a ecryptfs fille system.

Thanks a lot.

**Comment by sstone** [comment]
I cannot find commit 6d7717c in your fork, and the jar name should be eclair-node_2.11-0.2-SNAPSHOT-64c656c7-capsule-fat.jar.
Can you please try with our master branch (you should be able to compile on ecryptfs if you clone the source directory in /tmp) ? 
Also, which version of jdk and bitcoin core are you using ?
Thanks

**Comment by fjrojasgarcia** [comment]
I'm trying with your **master branch**;

```
git branch -vv
* master 3fc25da [origin/master] now using akka-http-json and akka-http-client (removed acinq-tools dependency)
```

_**~/.bitcoin/bitcoin.conf**_
```
server=1
regtest=1
rpcuser=***
rpcpassword=***
```

**_bitcoin-cli getblockchaininfo_**
...
```
  "bip9_softforks": {
    "csv": {
      "status": "active",
      "startTime": 0,
      "timeout": 999999999999
    },
    "segwit": {
      "status": "active",
      "startTime": 0,
      "timeout": 999999999999
    }
  }
}

```

**_df -T /shared/eclair/_**
```
S.ficheros                   Tipo bloques de 1K   Usados Disponibles Uso% Montado en
/dev/mapper/kubuntu--vg-root ext4     117983112 23351004    88595836  21% /
```

**_java -version_**
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```


**_mvn package -DskipTests_**
....
```
[INFO] eclair_2.11 ........................................ SUCCESS [  1.505 s]
[INFO] lightning-types_2.11 ............................... SUCCESS [01:10 min]
[INFO] eclair-node_2.11 ................................... SUCCESS [01:26 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:38 min
[INFO] Finished at: 2016-11-14T16:10:25+01:00
[INFO] Final Memory: 33M/245M
[INFO] ------------------------------------------------------------------------
```

**_cd eclair-node/target_**
```
java -jar eclair-node_2.11-0.2-SNAPSHOT-3fc25da-capsule-fat.jar
cassini 2016-11-14 16:12:32,133 INFO  fr.acinq.eclair.Setup  - hello!
cassini 2016-11-14 16:12:32,880 INFO  fr.acinq.eclair.Setup  - nodeid=03befb4f8ad1d87d4c41acbb316791fe157f305caf2123c848f448975aaf85c1bb
cassini 2016-11-14 16:12:33,167 INFO  akka.event.slf4j.Slf4jLogger  - Slf4jLogger started
cassini 2016-11-14 16:12:35,145 ERROR fr.acinq.eclair.gui.FxApp  - Something wrong happened: akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/json
	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:155)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:111)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:108)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$16$$anonfun$apply$17.apply(Unmarshaller.scala:88)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$16$$anonfun$apply$17.apply(Unmarshaller.scala:88)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23
```

Thanks for you patience

**Comment by sstone** [comment]
You can get this type of error if eclair cannot connect to bitcoin-core (in which case bitcoin-core returns a 401 a not the expected json response).
You must tell eclair which rpc user/password to use to connect to bitcoind. A good way of doing that is to create a configuration file (we use typesafe's [config library](https://github.com/typesafehub/config) and specify its path when you start eclair.

For example, you can start from the following configuration file (saved under $HOME/A.conf)(with   values for rpc user/password that match what you've configured in bitcoin.conf of course)
```
include "application"

eclair {
  server {
    port = 45001
  }
  api {
    port = 8081
  }
  bitcoind {
    port = 18444
    rpcport = 18332
    rpcuser = "foo"
    rpcpassword = "bar"
  }
  node {
    seed = 0102030405060708010203040506070801020304050607080102030405060708
  }
```

and start eclair like this:
```
java -Dconfig.file=$HOME/A.conf -jar eclair-node_2.11-0.2-SNAPSHOT-3fc25da-capsule-fat.jar
```

This way you can start multiple nodes at the same time.

Can you please try this and tell us if it works for you ?

**Comment by fjrojasgarcia** [comment]
**voilà**

 ```
java -Dconfig.file=$HOME/A.conf -jar eclair-node_2.11-0.2-SNAPSHOT-3fc25da-capsule-fat.jar
cassini 2016-11-14 17:09:08,302 INFO  fr.acinq.eclair.Setup  - hello!
cassini 2016-11-14 17:09:09,053 INFO  fr.acinq.eclair.Setup  - nodeid=03befb4f8ad1d87d4c41acbb316791fe157f305caf2123c848f448975aaf85c1bb
cassini 2016-11-14 17:09:09,283 INFO  akka.event.slf4j.Slf4jLogger  - Slf4jLogger started
cassini 2016-11-14 17:09:11,414 INFO  fr.acinq.eclair.io.Server akka://default/user/server - bound on Bound(/127.0.0.1:45001)
cassini 2016-11-14 17:09:11,432 INFO  f.a.e.blockchain.peer.PeerHandler akka://default/user/bitcoin-peer/peer-supervisor/peer-conn - connected to localhost/127.0.0.1:18444
cassini 2016-11-14 17:09:21,121 INFO  f.a.eclair.router.NodeIRCListener  - connected to IRC: IRCServerInfo (client=IRCClient (name=Unnamed, server=irc.freenode.net/130.185.232.126:6697))
```

**_The A.conf need a close brace._**

**Comment by sstone** [comment]
Thanks, I've added the missing brace.
