### ISSUE TITLE
Do not crash when regtest isn't up yet

### ISSUE THREAD

**Issue by NicolasDorier** [ACINQ/eclair#2180]
Version 0.7.0

I am unable to test eclair properly on https://github.com/btcpayserver/BTCPayServer.Lightning because it crashes as soon as the regtest is up. Instead please consider to wait and retry.

We are disabling tests of Eclair because of that.

**Comment by NicolasDorier** [comment]
```
2022-02-16 05:04:07,216 INFO  fr.acinq.eclair.Setup - using chain=regtest chainHash=06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f
fatal error: assertion failed: bitcoind should be synchronized (initialblockdownload=true)
2022-02-16 05:04:07,730 ERROR fr.acinq.eclair.Boot - fatal error: assertion failed: bitcoind should be synchronized (initialblockdownload=true)java.lang.AssertionError: assertion failed: bitcoind should be synchronized (initialblockdownload=true)
        at scala.Predef$.assert(Predef.scala:279)
        at fr.acinq.eclair.Setup.<init>(Setup.scala:193)
        at fr.acinq.eclair.Boot$.delayedEndpoint$fr$acinq$eclair$Boot$1(Boot.scala:44)
        at fr.acinq.eclair.Boot$delayedInit$body.apply(Boot.scala:34)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at fr.acinq.eclair.Boot$.main(Boot.scala:34)
        at fr.acinq.eclair.Boot.main(Boot.scala)
```

**Comment by t-bast** [comment]
We could make eclair spin until `bitcoind` is synchronized, but ignoring your test suite scenario and thinking about real users, that could take a while and makes a very weird user experience. Particularly on `regtest`, `bitcoind` has this weird behavior where you need to generate blocks to make it think that IBD is done.

Since a lightning node cannot do anything safely if `bitcoind` isn't synchronized, I believe it makes more sense to return an immediate error that tells the user they need to check their `bitcoind`. An alternative would be to respond with an error on every API request the user makes, saying `bitcoind` isn't ready yet.

How are you spinning up your tests? Is it just using docker and launching all containers? Wouldn't it make more sense to launch `bitcoind` first and only launch lightning nodes once `bitcoind` returns `initialblockdownload = false`? I'm afraid we'd just convert an immediate failure to a non-immediate one if eclair is just spinning forever because blocks needed to be generated for `bitcoind` regtest to consider the IBD done.

Note that this has nothing to do with version 0.7.0, this has been eclair's behavior for a couple of years, are you sure this was working before?

**Comment by t-bast** [comment]
We could probably have a different behavior for regtest vs testnet/mainnet.

I need to play around with that, but maybe we can disable that IBD check on `regtest`, since it doesn't really make sense anyway, and instead rely on a fixed number of retries (if we can't connect to `bitcoind` at all) before failing. Would that be better?

**Comment by NicolasDorier** [comment]
Closing this, the main problem about why my tests didn't start was about block hanging caused by misconfiguration of zmq. (was listening the raw block queue)
I think it would be nice for eclair to wait for initialblockdownload rather than exiting.

**Comment by NicolasDorier** [comment]
Just for explaining here: My tests are basically starting all dependencies (LND/Clightning/Eclair), 2 nodes each and connect two them together.

Then when my test start, it warmup regtest by mining a few blocks.
Because the test start after the docker-compose up, sometimes it fails because eclair is restarting.

**Comment by t-bast** [comment]
Gotcha, I'll take a stab at improving this next week.

**Comment by NicolasDorier** [comment]
@t-bast to be clear, I think c-lightning and lnd crashes as well if synching. This is why we publish our own docker images which wait in a loop in the docker-entrypoint before running the exec.

That's not a big deal though, the tests pass most of the time. Just I think it would be better, specially in regtest.

**Comment by sstone** [comment]
There is also something that is specific to eclair (compared to c-ligthning or lnd): we don't include an onchain wallet but instead use bitcoin core's: so your bitcoin node must have a wallet (with the latest versions of bitcoin core a wallet must explicitly be created) and to be able to fund channels it must have "matured" coins, so we we start bitcoind for testing we create a wallet, a new address, and generate 150 blocks to that address.
