### ISSUE TITLE
BitcoinCoreClientSpec test fails in intellij

### ISSUE THREAD

**Issue by barrybecker4** [ACINQ/eclair#2288]
I expected the BitcoinCoreClientSpec test to pass when run in Intellij.

Failed with this message:
```
An exception or error caused a run to abort: Cannot run program "E:\projects\scala_projects\eclair\target\bitcoin-0.21.1\bin\bitcoind": CreateProcess error=2, The system cannot find the file specified 
java.io.IOException: Cannot run program "E:\projects\scala_projects\eclair\target\bitcoin-0.21.1\bin\bitcoind": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:85)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:117)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:116)
	at fr.acinq.eclair.blockchain.bitcoind.BitcoindService.startBitcoind(BitcoindService.scala:90)
	at fr.acinq.eclair.blockchain.bitcoind.BitcoindService.startBitcoind$(BitcoindService.scala:69)
	at fr.acinq.eclair.blockchain.bitcoind.BitcoinCoreClientSpec.startBitcoind(BitcoinCoreClientSpec.scala:46)
	at fr.acinq.eclair.blockchain.bitcoind.BitcoinCoreClientSpec.beforeAll(BitcoinCoreClientSpec.scala:51)
```

Found this using tip of master. Running on Windows, java 11.
I think the fix is simple. I will make a PR.

**Comment by t-bast** [comment]
Fixed by #2289
