### ISSUE TITLE
Variables in config not resolved

### ISSUE THREAD

**Issue by DerEwige** [ACINQ/eclair#2336]
fr/acinq/eclair/NodeParams.scala

Tested version:
Eclair v0.7.0

Description:
When trying to use variables in the config file (eg. ${eclair.router.path-finding.default}  in the default example config file)
This error happens:

2022-06-25 13:26:58,118 ERROR- could not start eclaircom.typesafe.config.ConfigException$NotResolved: need to Config#resolve() each config before using it, see the API docs for Config#resolve()
	at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java:1103)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:388)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:818)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:290)
	at fr.acinq.eclair.Boot$.delayedEndpoint$fr$acinq$eclair$Boot$1(Boot.scala:41)
	at fr.acinq.eclair.Boot$delayedInit$body.apply(Boot.scala:34)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at fr.acinq.eclair.Boot$.main(Boot.scala:34)
	at fr.acinq.eclair.Boot.main(Boot.scala)

Reproducing steps
Use the reference.conf as your eclair.conf

Possible Solution:
Call the .resolve() function when loading the config file
(line 112 in NodeParams.scala)

**Comment by t-bast** [comment]
> Use the reference.conf as your eclair.conf

That would be very surprising. You must have incorrectly overridden some of the configuration.

**Comment by DerEwige** [comment]
Yes I have looked at the master reference.conf
I've checked https://github.com/ACINQ/eclair/blob/v0.7.0/eclair-core/src/main/resources/reference.conf now.

These lines are also in the 0.7.0 version

      experiments {
        control = ${eclair.router.path-finding.default} {
          percentage = 100 // 100% of the traffic use the default configuration
        }
      }

${eclair.router.path-finding.default}  is not resolving for me.

I've added my eclair.conf (.txt added as it would not let me upload)
[eclair.conf.txt](https://github.com/ACINQ/eclair/files/9002582/eclair.conf.txt)

I've replaced passwords with ******* in the config file.
This file is not working for me without calling the resolve() function. 
But works when using it.

**Comment by DerEwige** [comment]
@pm47 

Actually no. 
I declare every value of eclair.router.path-finding.default in my config file.
And then reference it.

But after reading your comment it makes more sense to me now.

The original code works like this:
read the config from file
pass the config into load (with fallback)

my code does:
read the config from file
resolve every substittute in the config
pass the config into load (with fallback)

There might be an issue with conflictinc references in the file and the fallback config
That cause an resolution problem.

By explicitly calling resolve() on only my local config, it replaces all substitutes before passing it into load (with fallback)

**Comment by DerEwige** [comment]
@pm47 

I believe your fix is not correct.
You call the reslove() at the end but it should be before the fallback load:

    ConfigFactory.systemProperties()
      .withFallback(ConfigFactory.parseFile(new File(datadir, "eclair.conf")).resolve())
      .withFallback(ConfigFactory.load())
 
I am currently at work, so can't check my code on my private station right now.
I can send you my working code this evenng.

**Comment by pm47** [comment]
Ok, waiting for your feedback. Please comment further directly on the pull request.
