### ISSUE TITLE
Flaky test in StandardChannelIntegration*Spec  (txn-mempool-conflict)

### ISSUE THREAD

**Issue by remyers** [ACINQ/eclair#2869]
When I locally run `mvn test` I sometimes get a failure with the test `"punish a node that has published a revoked commit tx"`. I first saw this error while testing with bitcoind 27.1RC1 in PR #2862, but now I also see it after I rolled back to master at [3bb5f3e](https://github.com/ACINQ/eclair/commit/3bb5f3e9f21f9a4c88f1fd1aa33185116278d9bd) to test with bitcoind 26.1 .

I have also seen this error in `StandardChannelIntegrationWithEclairSignerSpec` which runs the same tests as `StandardChannelIntegrationSpec`.

The mempool acceptance error [`txn-mempool-conflict`](https://github.com/bitcoin/bitcoin/blob/080a47cb8a8db27328bbdf57aa80cc4b4127a370/src/validation.cpp#L822) in the stack trace indicates that a conflicting tx has already spent the commitment tx output used as an input for an `htlcSuccess` or `htlcTimeout` tx and the conflicting tx does not have RBF enabled.
```

StandardChannelIntegrationWithEclairSignerSpec:

- punish a node that has published a revoked commit tx *** FAILED ***
  java.lang.AssertionError: assertion failed: expected e9c4f9cee4357c1d5449bd3e531a2c0b65fa6769bbc409da48b408b98d275c68, found Failure(fr.acinq.eclair.blockchain.bitcoind.rpc.JsonRPCError: txn-mempool-conflict (code: -26))
  at scala.Predef$.assert(Predef.scala:279)
  at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:462)
  at akka.testkit.TestKitBase.expectMsg(TestKit.scala:438)
  at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:438)
  at akka.testkit.TestKit.expectMsg(TestKit.scala:973)
  at fr.acinq.eclair.integration.StandardChannelIntegrationSpec.$anonfun$new$19(ChannelIntegrationSpec.scala:628)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

I have seen it fail trying to publish both  `htlcSuccess.head` and `htlcTimeout.head` transactions
```
    bitcoinClient.publishTransaction(htlcSuccess.head).pipeTo(sender.ref)
    sender.expectMsg(htlcSuccess.head.txid) <<<
    bitcoinClient.publishTransaction(htlcTimeout.head).pipeTo(sender.ref)
    sender.expectMsg(htlcTimeout.head.txid)  <<<
```

**Comment by remyers** [comment]
This also occurred with bitcoind 26.1 so not related to 27.1. I've fixed it with PR #2871 .
