### ISSUE TITLE
Trouble launching Eclair on Windows

### ISSUE THREAD

**Issue by PRabahy** [ACINQ/eclair#301]
I'm having trouble launch eclair on Windows. I believe I followed the instructions at https://github.com/ACINQ/eclair/wiki/Install properly.

Java looks correct
```
C:\Users\PRabahy>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

I am using bitcoin-qt v0.15.0, and bitcoin.conf looks correct (for testnet)
```
disablewallet=1
rpcuser=generated_by_armory
rpcpassword=MySuperSecurePassword
server=1
#rpcport=18332
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
```

Bitcoin-qt shows that it is at block 1255403.

I used the exe to install it, but when I double click the icon on my desktop, I get the following:
![image](https://user-images.githubusercontent.com/429961/34179564-769fc900-e4d9-11e7-8159-bdc12894153f.png)

```
2017-12-19 16:26:03,175 INFO  akka.event.slf4j.Slf4jLogger   - Slf4jLogger started
2017-12-19 16:26:03,200 INFO  akka.event.slf4j.Slf4jLogger   - Slf4jLogger started
2017-12-19 16:26:03,204 INFO  fr.acinq.eclair.Setup   - hello!
2017-12-19 16:26:03,204 INFO  fr.acinq.eclair.Setup   - version=0.2-alpha7 commit=1155788b5e5e0757ca1ae54d7101008608df724f
2017-12-19 16:26:03,254 INFO  org.bitcoin.Secp256k1Context   - couldn't find secp256k1 library, defaulting to spongycastle
2017-12-19 16:26:03,671 INFO  fr.acinq.eclair.Setup   - nodeid=036578f8fb8be110c755f214876371dc93e4e8e1477bbe324d242d19ce3088c68a alias=eclair
2017-12-19 16:26:03,673 INFO  fr.acinq.eclair.Setup   - using chain=test chainHash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000
2017-12-19 16:26:03,673 INFO  fr.acinq.eclair.Setup   - initializing secure random generator
2017-12-19 16:26:05,125 ERROR fr.acinq.eclair.gui.FxPreloader   - An error has occured
```

**Comment by PRabahy** [comment]
I found https://github.com/ACINQ/eclair/blob/master/README.md#configuring-eclair and realized that I might not have configured eclair properly, so I did my best.

I found the folder C:\Users\PRabahy\.eclair, and it had 3 files in it. I didn't see the datadir that the README talked about, so I created it. Inside that I created eclair.conf with the following:

```
eclair.chain=test
eclair.node-alias=PRabahy
eclair.bitcoind.rpcport=18332
eclair.bitcoind.rpcuser=generated_by_armory
eclair.bitcoind.rpcpassword=MySuperSecurePassword
```

Still no luck...

**Comment by pm47** [comment]
Path to the configuration file should be: `C:\Users\PRabahy\.eclair\datadir\eclair.conf`, unless you have overriden the default directory?

**Comment by PRabahy** [comment]
I thought that would be the default configuration file. If its not, how do I override the default directory if I am using the exe?

**Comment by pm47** [comment]
You don't need to override the default directory, just put your `eclair.conf` in `C:\Users\PRabahy\.eclair`.

**Comment by PRabahy** [comment]
Ah, I misread
```
Eclair reads its configuration file, and write its logs, to a datadir directory, located in ~/.eclair by default.

To change your node's configuration, create a file named eclair.conf in datadir. 
```

to mean that there was a directory literally named `datadir`.

I am now getting 
![image](https://user-images.githubusercontent.com/429961/34182559-da08f43e-e4e4-11e7-8c48-7f640c727a3e.png)

**Comment by pm47** [comment]
What version is your bitcoin-core ?

**Comment by PRabahy** [comment]
v0.15.0 (64-bit)
![image](https://user-images.githubusercontent.com/429961/34182662-2ee63dd6-e4e5-11e7-978d-9eb17a79635a.png)

```
2017-12-19 17:47:20,406 INFO  fr.acinq.eclair.Setup   - nodeid=036578f8fb8be110c755f214876371dc93e4e8e1477bbe324d242d19ce3088c68a alias=PRabahy
2017-12-19 17:47:20,407 INFO  fr.acinq.eclair.Setup   - using chain=test chainHash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000
2017-12-19 17:47:20,407 INFO  fr.acinq.eclair.Setup   - initializing secure random generator
2017-12-19 17:47:21,600 ERROR fr.acinq.eclair.gui.FxPreloader   - An error has occuredfr.acinq.eclair.blockchain.bitcoind.rpc.JsonRPCError: Method not found (code: -32601)
	at fr.acinq.eclair.blockchain.bitcoind.rpc.BitcoinJsonRPCClient$$anonfun$invoke$1$$anonfun$apply$3$$anonfun$apply$4.apply(BitcoinJsonRPCClient.scala:62)
	at fr.acinq.eclair.blockchain.bitcoind.rpc.BitcoinJsonRPCClient$$anonfun$invoke$1$$anonfun$apply$3$$anonfun$apply$4.apply(BitcoinJsonRPCClient.scala:61)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by PRabahy** [comment]
I was suspicious that this might have been caused by adding `txindex=1` after bitcoin had been running for a while, so I ran a reindex. Unfortunately, that didn't fix the issue.

**Comment by sstone** [comment]
> I am using bitcoin-qt v0.15.0, and bitcoin.conf looks correct (for testnet)
> `disablewallet=1`

It seems that your bitcoin wallet is disabled, eclair will not be able to work properly (wallet-related RPC calls will fail with a `method not found` error). Can you enable the wallet and try again ?

**Comment by PRabahy** [comment]
Ok, I think that last tip helped me figure it out.

1. I didn't realize that I needed the wallet enabled. Usually I use Armory, so I keep the bitcoin core wallet disabled.
2. I was accidentally using the wrong config file. I assumed that if I launched bitcoin-qt with `-testnet`, it would automatically use C:\Users\PRabahy\AppData\Roaming\Bitcoin\testnet3\bitcoin.conf. Looks like the better option is to just pass `-conf=C:\Users\PRabahy\AppData\Roaming\Bitcoin\testnet3\bitcoin.conf` and set `testnet=1` in there.

I now need to re-index again (eclair is now saying "bitcoind should be synchronized"), but I think I'm all set. I'll close this issue if it works as expected after the re-index finishes.

**Comment by PRabahy** [comment]
Yep that did it!
