### ISSUE TITLE
Error then eclair restarted: make sure that all your UTXOs are p2sh-of-p2wpkh (check out our README for more details)

### ISSUE THREAD

**Issue by ew4by** [ACINQ/eclair#311]
Subj.
I shutdown eclair and run it again after it was started and worked and get this error:
2017-12-21 06:30:02,059 INFO  akka.event.slf4j.Slf4jLogger   - Slf4jLogger started
2017-12-21 06:30:02,120 INFO  akka.event.slf4j.Slf4jLogger   - Slf4jLogger started
2017-12-21 06:30:02,138 INFO  fr.acinq.eclair.Setup   - hello!
2017-12-21 06:30:02,139 INFO  fr.acinq.eclair.Setup   - version=0.2-alpha7 commit=1155788b5e5e0757ca1ae54d7101008608df724f
2017-12-21 06:30:02,257 INFO  org.bitcoin.Secp256k1Context   - couldn't find secp256k1 library, defaulting to spongycastle
2017-12-21 06:30:03,206 INFO  fr.acinq.eclair.Setup   - nodeid=02e1b75e78b209e0485fee3576b742ed0cb4d92cba043f15bb52de2253e418e74a alias=eclair
2017-12-21 06:30:03,207 INFO  fr.acinq.eclair.Setup   - using chain=test chainHash=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000
2017-12-21 06:30:03,208 INFO  fr.acinq.eclair.Setup   - initializing secure random generator
2017-12-21 06:30:06,129 ERROR fr.acinq.eclair.gui.FxPreloader   - An error has occuredjava.lang.AssertionError: assertion failed: In testnet mode, make sure that all your UTXOs are p2sh-of-p2wpkh (check out our README for more details)
	at scala.Predef$.assert(Predef.scala:170)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:79)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:66)
	at java.lang.Thread.run(Thread.java:745)

Nothing in the settings has not changed, but I can not start the eclair any more.
Even if you delete the ./eclear directory
And where is README ??? =)))

**Comment by dpad85** [comment]
Here's the README: https://github.com/ACINQ/eclair/blob/master/README.md

In the [Configure Bitcoin-core](https://github.com/ACINQ/eclair/blob/master/README.md#configuring-bitcoin-core) section, you'll find:

> On testnet, you also need to make sure that all your UTXOs are p2sh-of-p2wpkh. To do this, use the debug console, create a new address with getnewaddress, import it as a witness address with addwitnessaddress, and send all your balance to this witness address. If you need to create and send funds manually, don't forget to create and specify a witness address for the change output (this option is avaliable on the GUI once you set the Enable coin control features wallet option).

What happened is that you sent a tx to your bitcoin core from a non segwit wallet and some of your unspent outputs are not p2sh-of-p2wpkh.

For this kind of issue, please go to our gitter: https://gitter.im/ACINQ/eclair
