### ISSUE TITLE
requirement failed: invalid mac

### ISSUE THREAD

**Issue by deafboy** [ACINQ/eclair#409]
On one of my nodes my eclair.log is constantly filled with these errors. Since it began I've made a clean build (switched from alpha8 to alpha9), I even opened a channel with one of the problematic IPs from my other node but couldn't reproduce it.

`2018-01-25 17:32:03,335 INFO  fr.acinq.eclair.io.Server akka://default/user/$j/server  - connected to /213.32.48.249:58958
2018-01-25 17:32:03,391 ERROR akka.actor.OneForOneStrategy akka://default/user/$h/authenticator/$lB  - requirement failed: invalid macjava.lang.IllegalArgumentException: requirement failed: invalid mac
	at scala.Predef$.require(Predef.scala:224)
	at fr.acinq.eclair.crypto.ChaCha20Poly1305$.decrypt(ChaCha20Poly1305.scala:109)
	at fr.acinq.eclair.crypto.Noise$Chacha20Poly1305CipherFunctions$.decrypt(Noise.scala:95)
	at fr.acinq.eclair.crypto.Noise$InitializedCipherState.decryptWithAd(Noise.scala:195)
	at fr.acinq.eclair.crypto.Noise$SymmetricState.decryptAndHash(Noise.scala:235)
	at fr.acinq.eclair.crypto.Noise$HandshakeStateReader.read(Noise.scala:398)
	at fr.acinq.eclair.crypto.TransportHandler$$anonfun$1.applyOrElse(TransportHandler.scala:77)
	at fr.acinq.eclair.crypto.TransportHandler$$anonfun$1.applyOrElse(TransportHandler.scala:67)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:663)
	at fr.acinq.eclair.crypto.TransportHandler.processEvent(TransportHandler.scala:31)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
	at fr.acinq.eclair.crypto.TransportHandler.aroundReceive(TransportHandler.scala:31)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

https://pastebin.com/B9rLrw0T

**Comment by pm47** [comment]
It seems that your node is publicly reachable, and eclair fails to decrypt data sent by those ips. It may be a bug in eclair, or it may be a bug in the remote peer, or that might not even be lightning traffic (although in that case connection should have failed before).

Were any of these ips legit peers of your node before the upgrade?

**Comment by deafboy** [comment]
>Were any of these ips legit peers of your node before the upgrade?

Hard to tell now, but it's likely. At least 213.32.48.249 (mocanode) kinda rings a bell.

**Comment by pm47** [comment]
I may have an idea. When you upgraded from alpha8 to alpha9, did you delete your whole `.eclair` directory or just the `eclair.sqlite` file?

If you deleted the whole directory, then your node has generated a a new seed and now has a different `node_id`. It is possible that these old peers are trying to re-connect to your node using your previous `node_id`, which causes the authentication to fail.

If that is what happened, then it is annoying but harmless and there isn't anything that can be done unfortunately, apart from waiting for those nodes to give up (or blacklisting them in your firewall).

We should definitely have provided guidelines on how to proceed when upgrading.

**Comment by deafboy** [comment]
I've removed the whole .eclair directory.

**Comment by pm47** [comment]
I think we have the explanation, there is nothing to fix so I'm closing this.

We'll be more explicit next time we break backwards compatibility.
