### ISSUE TITLE
Could not connect to Bitcoin Core using ZMQ

### ISSUE THREAD

**Issue by jnsu** [ACINQ/eclair#435]
Log says

```
ERROR fr.acinq.eclair.gui.FxPreloader   - fr.acinq.eclair.BitcoinZMQConnectionTimeoutException$: could     not connect to bitcoind using zeromq
  at fr.acinq.eclair.BitcoinZMQConnectionTimeoutException$.<clinit>(Setup.scala)
  at fr.acinq.eclair.Setup$$anonfun$22.apply(Setup.scala:177)
  at fr.acinq.eclair.Setup$$anonfun$22.apply(Setup.scala:177)
```

Here is my bitcoinf.conf.
```
rpcuser=foo
rpcpassword=bar
testnet=1
server=1
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
daemon=1
```

Has anyone encounter this error?

**Comment by jnsu** [comment]
I had to install zmq in prior to building bitcoin core.
