### ISSUE TITLE
Only able to open first channel, all others disappear, tried dozens

### ISSUE THREAD

**Issue by btcb0b** [ACINQ/eclair#458]
Terminal showing new channel created and opened:
https://pastebin.com/2AyAk4Vj

Eclair log after opening new channel
https://pastebin.com/57K0U5ug

Channels command shows that the new channel opened and created has disappeared:
https://pastebin.com/DxGaBtUU

My first channel connected, opened, and has persisted. I have tried to connect and open dozens since without success. My wallet has about 3.4 testcoins, and I have verified that it is unlocked while trying to create new channels

**Comment by n1bor** [comment]
I know you said you had 3.4 testcoins - but errors is that there are not enough...
Would check they are confirmed and on a segwit address.



2018-02-24 08:57:37,431 ERROR fr.acinq.eclair.channel.Channel akka://default/user/$h/switchboard/peer-0299ec4b40e55044f5c578512f6fa7161a7e1bc6d2638335a304c6f8607d2444aa/$d e13d7a5a24c42fa1b6f8ea262ca0372df493c1dfb800fe40b5015e65be7c94d9 - wallet returned error: fr.acinq.eclair.blockchain.bitcoind.rpc.JsonRPCError: Insufficient funds (code: -4)
    at fr.acinq.eclair.blockchain.bitcoind.rpc.BatchingClient$$anonfun$waiting$1$$anonfun$applyOrElse$2.apply(BatchingClient.scala:30)
    at fr.acinq.eclair.blockchain.bitcoind.rpc.BatchingClient$$anonfun$waiting$1$$anonfun$applyOrElse$2.apply(BatchingClient.scala:28)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at fr.acinq.eclair.blockchain.bitcoind.rpc.BatchingClient$$anonfun$waiting$1.applyOrElse(BatchingClient.scala:28)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
    at fr.acinq.eclair.blockchain.bitcoind.rpc.BatchingClient.aroundReceive(BatchingClient.scala:9)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
 
2018-02-24 08:57:47,451 INFO  fr.acinq.eclair.channel.Channel akka://default/user/$h/switchboard/peer-0299ec4b40e55044f5c578512f6fa7161a7e1bc6d2638335a304c6f8607d2444aa/$d e13d7a5a24c42fa1b6f8ea262ca0372df493c1dfb800fe40b5015e65be7c94d9 - shutting down

**Comment by btcb0b** [comment]
Thanks, added more coins and sent to a witness address and successfully opened a second channel
