### ISSUE TITLE
Eclair-0.2-beta1.exe Error: Futures timed out after [10 seconds]

### ISSUE THREAD

**Issue by hopitas** [ACINQ/eclair#529]
I'm trying to test new Eclair on mainnet with my Windows machine. I got bitcoind running on another linux machine and I have checked that I can reach it with rpc/zmq. Still I get:

Error: Futures timed out after [10 seconds]

Should Eclair Eclair-0.2-beta1.exe work with mainnet yet?

Here is my eclair conf:

eclair.chain=mainnet
eclair.bitcoind.host = xxx.xxx.xxx.xxx
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=xxx
eclair.bitcoind.rpcpassword=xxx
eclair.bitcoind.zmq="tcp://xxx.xxx.xxx.xxx:29000"

bitcoind conf:

rpcuser=xxx
rpcpassword=xxx
rpcallowip=xxx.xxx.xxx.xxx
daemon=1
txindex=1
zmqpubrawblock=tcp://\*:29000
zmqpubrawtx=tcp://\*:29000
addresstype=p2sh-segwit

eclair.log:

2018-04-03 09:24:54,239 INFO  akka.event.slf4j.Slf4jLogger   - Slf4jLogger started
2018-04-03 09:24:54,253 INFO  fr.acinq.eclair.Setup   - hello!
2018-04-03 09:24:54,254 INFO  fr.acinq.eclair.Setup   - version=0.2-beta1 commit=c39ce692f86f0fc98d92e58d013ec2b6d69c8cf5
2018-04-03 09:24:54,255 INFO  fr.acinq.eclair.Setup   - datadir=C:\Users\xxxx\ .eclair
2018-04-03 09:24:54,352 INFO  org.bitcoin.Secp256k1Context   - couldn't find secp256k1 library, defaulting to spongycastle
2018-04-03 09:24:54,958 INFO  fr.acinq.eclair.Setup   - nodeid=02612b511b73b86ff211d6853ba6f702b3c9e3318c944c5130fce1d02dfa8eeef2 alias=eclair
2018-04-03 09:24:54,958 INFO  fr.acinq.eclair.Setup   - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2018-04-03 09:24:54,959 INFO  fr.acinq.eclair.Setup   - initializing secure random generator
2018-04-03 09:25:06,125 ERROR fr.acinq.eclair.gui.FxPreloader   - java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:105)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:86)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pm47** [comment]
This looks like a configuration issue, related to rpc. A little more details on your setup would help. It could also simply be that connection between your two computers is very slow.

I would recommend that you start with bitcoin+eclair on the same machine, and try more fancy stuff later. Note that from a performance point of view (especially initial validation of routing table), separating bitcoin core and eclair is probably not a great idea.

**Comment by hopitas** [comment]
Ok. I might try running both on same machine. Just seems a bit of waste to have to download and store blockchain on multiple machines...

I have a separate bitcoind linux machine and tried to connect eclair to that. Is there then way to run eclair daemon and bitcoind on same machine and just the gui on another machine?

I checked that rpc commands go through... I would guess many people run bitcoind in a separate server machine? How is eclair android app going to work?

Thanks for reply :)

**Comment by hopitas** [comment]
Ok it was rpc port blocked. Seems to be working fine now :D
