### ISSUE TITLE
scala.NotImplementedError: an implementation is missing

### ISSUE THREAD

**Issue by fogonthedowns** [ACINQ/eclair#630]
```
java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

I'm using `eclair-node-gui-0.2-beta4-e6fe077.jar`

I see this over and over in my logs:

```
2018-06-17 10:10:54,330 ERROR akka.actor.ActorCell akka://default/user/$g/router  - changing Resume into Create after akka.actor.ActorInitializationException: akka://default/user/$g/router: exception during creation
2018-06-17 10:10:54,330 INFO  fr.acinq.eclair.router.Router akka://default/user/$g/router  - loading network announcements from db...
2018-06-17 10:10:54,330 INFO  fr.acinq.eclair.router.Router akka://default/user/$g/router  - loaded from db: channels=0 nodes=0 updates=0
2018-06-17 10:10:54,330 ERROR fr.acinq.eclair.SimpleSupervisor akka://default/user/$g  - supervisor caught error for child=router strategy=Resume akka.actor.ActorInitializationException: akka://default/user/$g/router: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:374)
	at akka.actor.dungeon.FaultHandling$class.faultResume(FaultHandling.scala:102)
	at akka.actor.ActorCell.faultResume(ActorCell.scala:374)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:466)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:230)
	at fr.acinq.eclair.wire.NodeAddress$.apply(LightningMessageTypes.scala:166)
	at fr.acinq.eclair.router.Announcements$$anonfun$1.apply(Announcements.scala:80)
	at fr.acinq.eclair.router.Announcements$$anonfun$1.apply(Announcements.scala:80)
	at scala.collection.immutable.List.map(List.scala:284)
	at fr.acinq.eclair.router.Announcements$.makeNodeAnnouncement(Announcements.scala:80)
	at fr.acinq.eclair.router.Router.<init>(Router.scala:131)
	at fr.acinq.eclair.router.Router$$anonfun$props$1.apply(Router.scala:550)
	at fr.acinq.eclair.router.Router$$anonfun$props$1.apply(Router.scala:550)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:374)
	at akka.actor.dungeon.FaultHandling$class.faultResume(FaultHandling.scala:102)
	at akka.actor.ActorCell.faultResume(ActorCell.scala:374)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:466)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
```

**Comment by fogonthedowns** [comment]
Sorry this is invalid, I was setting `eclair.server.public-ips=[“xx.xx.xx.xx”]` These logs went away when I removed this.

**Comment by sstone** [comment]
We need to improve error handling in this case
