### ISSUE TITLE
java.lang.NoSuchMethodError: org.spongycastle.crypto.engines.ChaCha7539Engine.packTauOrSigma(I[II)V

### ISSUE THREAD

**Issue by Christewart** [ACINQ/eclair#643]
Currently seeing an error where ChaCha739Engine.packTauOrSigma is missing on my classpath. 

> 18:26:02.103 TKD [default-akka.actor.default-dispatcher-4] INFO  fr.acinq.eclair.io.Client - connected to pubkey=020a5f6f4456d3f3ffd1e731b208269ea02db2c1d4bfbeb432f9a612fe58a77cfa host=localhost port=2442
18:26:02.106 TKD [default-akka.actor.default-dispatcher-7] INFO  fr.acinq.eclair.io.Server - connected to /127.0.0.1:60466
Uncaught error from thread [default-akka.actor.default-dispatcher-14]: org.spongycastle.crypto.engines.ChaCha7539Engine.packTauOrSigma(I[II)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[default]
java.lang.NoSuchMethodError: org.spongycastle.crypto.engines.ChaCha7539Engine.packTauOrSigma(I[II)V
        at org.spongycastle.crypto.engines.ChaCha7539Engine.setKey(ChaCha7539Engine.java:105)
        at org.spongycastle.crypto.engines.Salsa20Engine.init(Salsa20Engine.java:111)
        at fr.acinq.eclair.crypto.ChaCha20$.encrypt(ChaCha20Poly1305.scala:55)
        at fr.acinq.eclair.crypto.ChaCha20Poly1305$.encrypt(ChaCha20Poly1305.scala:104)
        at fr.acinq.eclair.crypto.Noise$Chacha20Poly1305CipherFunctions$.encrypt(Noise.scala:103)
        at fr.acinq.eclair.crypto.Noise$InitializedCipherState.encryptWithAd(Noise.scala:208)
        at fr.acinq.eclair.crypto.Noise$SymmetricState.encryptAndHash(Noise.scala:246)
        at fr.acinq.eclair.crypto.Noise$HandshakeStateWriter.write(Noise.scala:358)
        at fr.acinq.eclair.crypto.TransportHandler.<init>(TransportHandler.scala:65)
        at fr.acinq.eclair.crypto.TransportHandler$$anonfun$props$1.apply(TransportHandler.scala:233)
        at fr.acinq.eclair.crypto.TransportHandler$$anonfun$props$1.apply(TransportHandler.scala:233)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:563)
        at akka.actor.ActorCell.create(ActorCell.scala:589)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
18:26:02.199 TKD [default-akka.actor.default-dispatcher-2] ERROR akka.actor.ActorSystemImpl - Uncaught error from thread [default-akka.actor.default-dispatcher-14]: org.spongycastle.crypto.engines.ChaCha7539Engine.packTauOrSigma(I[II)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.NoSuchMethodError: org.spongycastle.crypto.engines.ChaCha7539Engine.packTauOrSigma(I[II)V
        at org.spongycastle.crypto.engines.ChaCha7539Engine.setKey(ChaCha7539Engine.java:105)
        at org.spongycastle.crypto.engines.Salsa20Engine.init(Salsa20Engine.java:111)
        at fr.acinq.eclair.crypto.ChaCha20$.encrypt(ChaCha20Poly1305.scala:55)
        at fr.acinq.eclair.crypto.ChaCha20Poly1305$.encrypt(ChaCha20Poly1305.scala:104)
        at fr.acinq.eclair.crypto.Noise$Chacha20Poly1305CipherFunctions$.encrypt(Noise.scala:103)
        at fr.acinq.eclair.crypto.Noise$InitializedCipherState.encryptWithAd(Noise.scala:208)
        at fr.acinq.eclair.crypto.Noise$SymmetricState.encryptAndHash(Noise.scala:246)
        at fr.acinq.eclair.crypto.Noise$HandshakeStateWriter.write(Noise.scala:358)
        at fr.acinq.eclair.crypto.TransportHandler.<init>(TransportHandler.scala:65)
        at fr.acinq.eclair.crypto.TransportHandler$$anonfun$props$1.apply(TransportHandler.scala:233)
        at fr.acinq.eclair.crypto.TransportHandler$$anonfun$props$1.apply(TransportHandler.scala:233)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
        at akka.actor.Props.newActor(Props.scala:213)
        at akka.actor.ActorCell.newActor(ActorCell.scala:563)
        at akka.actor.ActorCell.create(ActorCell.scala:589)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by sstone** [comment]
Can you provide more details on how to reproduce ? Is it with the standard version of eclair  and if so which version ? It looks like a version old version of spongycastle (1.54?) is found at runtime instead of the one we need  (1.58)

**Comment by Christewart** [comment]
I'm working off of #633 . I've published that PRto my local artifactory with 

``` 
$ mvn install -DskipTests &
```

When I do `show dependencyClasspath` in sbt (the project I am using the eclair dep in a sbt project) the only instance of spongy castle I see in my classpath is 

```
Attributed(/home/chris/.ivy2/cache/com.madgag.spongycastle/core/jars/core-1.58.0.0.jar)
```

Here is the build of eclair in maven: 

https://pastebin.com/Cc48KHmW

There is this suspicious line from sbt that I am trying to investigate further, I'm not sure what exactly is happening here: 

```
[info] Updating {file:/home/chris/dev/suredbits-api/}api...
[info] Resolving fr.acinq.eclair#eclair-node_2.11;0.2-SB-SNAPSHOT ...
[warn] Unable to reparse fr.acinq.eclair#eclair-node_2.11;0.2-SB-SNAPSHOT from Maven2 Local, using Mon Jun 25 19:23:41 CDT 2018
[info] Resolving fr.acinq.eclair#eclair-core_2.11;0.2-SB-SNAPSHOT ...
[warn] Unable to reparse fr.acinq.eclair#eclair-core_2.11;0.2-SB-SNAPSHOT from Maven2 Local, using Mon Jun 25 19:25:39 CDT 2018
```

**Comment by Christewart** [comment]
This is resolved now, but i'm not sure how I resolved it. I explictly added `spongycastle` to the `eclair-core` and `eclair-node` projects which might have done this trick. I'll close for now.
