### ISSUE TITLE
Eclair does not work with new BTC Core 0.17?

### ISSUE THREAD

**Issue by STAWKEYE** [ACINQ/eclair#726]
See below for log file upon startup. Popup error "Error: assertion failed: Eclair requires Bitcoin Core 0.16.0 or higher"

2018-10-03 13:29:52,181 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2018-10-03 13:29:52,201 INFO  fr.acinq.eclair.Setup  - hello!
2018-10-03 13:29:52,202 INFO  fr.acinq.eclair.Setup  - version=0.2-beta6 commit=3fc5da0a7b612b01fdcd2bc5f009996f69ab5e7b
2018-10-03 13:29:52,203 INFO  fr.acinq.eclair.Setup  - datadir=C:\Users\The Hive\.eclair
2018-10-03 13:29:52,339 INFO  o.b.Secp256k1Context  - couldn't find secp256k1 library, defaulting to spongycastle
2018-10-03 13:29:57,637 INFO  fr.acinq.eclair.Setup  - nodeid=02065e25c272203440b66ea0ba66601d1248564554d0a68472b82511af54288120 alias=Platform9and3quarters
2018-10-03 13:29:57,638 INFO  fr.acinq.eclair.Setup  - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2018-10-03 13:29:57,638 INFO  fr.acinq.eclair.Setup  - initializing secure random generator
2018-10-03 13:29:59,246 ERROR f.a.e.gui.FxPreloader  - java.lang.AssertionError: assertion failed: Eclair requires Bitcoin Core 0.16.0 or higher
	at scala.Predef$.assert(Predef.scala:170)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:113)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:87)
	at java.lang.Thread.run(Thread.java:748)

**Comment by STAWKEYE** [comment]
UPDATE: My apologies - I see a pull request: "Support for bitcoin 0.17.x #682" and so I guess this is already in the works.

**Comment by sstone** [comment]
Yes, there are behaviour and API changes in 0.17 which is why it's not as simple as changing the version check (and we'll need to maintain compatibility with 0.16.3 for people who will not upgrade right away).

**Comment by nopara73** [comment]
> You can use the `deprecatedrpc` functionality to retain old behavior while still upgrading (making you acknowledge that the behavior will be removed in a later release).

https://github.com/bitcoin/bitcoin/issues/14363#issuecomment-426855205

**Comment by gustavonalle** [comment]
You can use 0.17 by passing ```-deprecatedrpc=signrawtransaction``` param to bitcoind/bitcoin-qt
