### ISSUE TITLE
Restoring Eclair 0.2-beta8

### ISSUE THREAD

**Issue by tukac** [ACINQ/eclair#770]
How to restore? My mainnet node went belly up! Out of the blue!

Message:
"Breaking changes! Eclair is still in alpha, and under heavy development. Last update was not backward compatible. Please reset your datadir."

Dang! I have set it up nicely, several channels with some money on line. Would be nice if I can get it back...

Core 0.17.0.1, Eclair 02.-beta8, Win 10

**Comment by pm47** [comment]
Did you hard drive get full? Did eclair crash? Is there anything interesting in the logs?

**Comment by tukac** [comment]
Yup.
2018-12-02 21:25:18,905 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2018-12-02 21:25:19,095 INFO  fr.acinq.eclair.Setup  - hello!
2018-12-02 21:25:19,097 INFO  fr.acinq.eclair.Setup  - version=0.2-beta8 commit=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2018-12-02 21:25:19,099 INFO  fr.acinq.eclair.Setup  - datadir=C:\Users\User\.eclair
2018-12-02 21:25:19,647 INFO  o.b.Secp256k1Context  - couldn't find secp256k1 library, defaulting to spongycastle
2018-12-02 21:25:22,239 INFO  a.e.slf4j.Slf4jLogger  - Slf4jLogger started
2018-12-02 21:25:22,282 INFO  fr.acinq.eclair.Setup  - hello!
2018-12-02 21:25:22,284 INFO  fr.acinq.eclair.Setup  - version=0.2-beta8 commit=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2018-12-02 21:25:22,287 INFO  fr.acinq.eclair.Setup  - datadir=C:\Users\User\.eclair
2018-12-02 21:25:22,627 INFO  o.b.Secp256k1Context  - couldn't find secp256k1 library, defaulting to spongycastle
2018-12-02 21:25:23,059 ERROR f.a.e.gui.FxPreloader  - fr.acinq.eclair.IncompatibleDBException$: database is not compatible with this version of eclair
	at fr.acinq.eclair.IncompatibleDBException$.<clinit>(Setup.scala)
	at fr.acinq.eclair.DBCompatChecker$.checkDBCompatibility(DBCompatChecker.scala:33)
	at fr.acinq.eclair.Setup.<init>(Setup.scala:73)
	at fr.acinq.eclair.gui.FxApp$$anon$2.run(FxApp.scala:87)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pm47** [comment]
This only shows what happens *after* the database has been corrupted, but do you have logs at the moment where the problem actually occured?

Is your hard drive full?

**Comment by tukac** [comment]
Drive has plenty of space.
Logs from immediately before:
2018-12-02 21:24:18,176 INFO  fr.acinq.eclair.io.Peer  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - sent announcements to 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf: channels=0 updates=149 nodes=1
2018-12-02 21:24:18,176 INFO  fr.acinq.eclair.io.Peer  n:03fc5b91ce2d857f146fd9b986363374ffe04dc143d8bcd6d7664c8873c463cdfc - sent announcements to 03fc5b91ce2d857f146fd9b986363374ffe04dc143d8bcd6d7664c8873c463cdfc: channels=0 updates=15 nodes=0
2018-12-02 21:24:18,176 INFO  fr.acinq.eclair.io.Peer  n:032a438e14dde2082aefd287d52664d3ac99c395a99d5e6a87f38778515fad75f7 - sent announcements to 032a438e14dde2082aefd287d52664d3ac99c395a99d5e6a87f38778515fad75f7: channels=0 updates=12 nodes=0
2018-12-02 21:24:18,786 INFO  f.a.eclair.router.Router  n:03b1ba0b913b793b4de77c9fbb5ed3bfc3897e247113b3c2d7d34fed0895ad4e1e - received reply_short_channel_ids_end=ReplyShortChannelIdsEnd(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,1)
2018-12-02 21:24:18,786 INFO  f.a.eclair.router.Router  n:03b1ba0b913b793b4de77c9fbb5ed3bfc3897e247113b3c2d7d34fed0895ad4e1e - asking 03b1ba0b913b793b4de77c9fbb5ed3bfc3897e247113b3c2d7d34fed0895ad4e1e for the next slice of short_channel_ids
2018-12-02 21:24:19,282 INFO  f.a.eclair.router.Router  n:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f - received reply_channel_range, we're missing 0 channel announcements/updates, format=0 useGzip=false
2018-12-02 21:24:19,597 INFO  f.a.eclair.router.Router  n:02911515d46e371eacb87dbd5f513b03ab23031d17c3668293a8cca5369072dbea - received reply_channel_range, we're missing 0 channel announcements/updates, format=0 useGzip=false
2018-12-02 21:24:25,150 INFO  f.a.eclair.router.Router  n:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f - received reply_channel_range, we're missing 0 channel announcements/updates, format=0 useGzip=false
2018-12-02 21:24:25,174 INFO  f.a.eclair.router.Router  n:03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f - received query_short_channel_ids for 13 channel announcements, useGzip=false
2018-12-02 21:24:25,410 INFO  f.a.eclair.Diagnostics  n:02911515d46e371eacb87dbd5f513b03ab23031d17c3668293a8cca5369072dbea c:f9f0fbb35c42a3447bab7e442bf2fcd100e7725e63a60f993dd648656ed77532 - IN msg=Error(f9f0fbb35c42a3447bab7e442bf2fcd100e7725e63a60f993dd648656ed77532,73796e63206572726f72)
2018-12-02 21:24:25,411 WARN  f.a.e.channel.Channel  n:02911515d46e371eacb87dbd5f513b03ab23031d17c3668293a8cca5369072dbea c:f9f0fbb35c42a3447bab7e442bf2fcd100e7725e63a60f993dd648656ed77532 - unhandled event Error(f9f0fbb35c42a3447bab7e442bf2fcd100e7725e63a60f993dd648656ed77532,73796e63206572726f72) in state WAIT_FOR_REMOTE_PUBLISH_FUTURE_COMMITMENT
2018-12-02 21:24:25,453 INFO  f.a.eclair.router.Router  n:02911515d46e371eacb87dbd5f513b03ab23031d17c3668293a8cca5369072dbea - received reply_channel_range, we're missing 3 channel announcements/updates, format=0 useGzip=false
2018-12-02 21:24:26,886 INFO  f.a.e.c.TransportHandler  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - connection closed: ErrorClosed(An existing connection was forcibly closed by the remote host)
2018-12-02 21:24:26,887 INFO  fr.acinq.eclair.io.Peer  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - lost connection to 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf
2018-12-02 21:24:27,896 INFO  f.acinq.eclair.io.Client  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - connecting to pubkey=03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf host=13.92.254.226 port=9735
2018-12-02 21:24:31,767 INFO  f.a.e.c.TransportHandler  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - connection closed: ErrorClosed(An existing connection was forcibly closed by the remote host)
2018-12-02 21:24:31,767 INFO  fr.acinq.eclair.io.Peer  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - lost connection to 0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4
2018-12-02 21:24:32,780 INFO  f.acinq.eclair.io.Client  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - connecting to pubkey=0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 host=51.15.123.173 port=9735
2018-12-02 21:24:32,919 INFO  f.acinq.eclair.io.Client  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - connection failed to 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf@13.92.254.226:9735
2018-12-02 21:24:37,495 INFO  f.acinq.eclair.io.Client  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - connected to pubkey=0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 host=51.15.123.173 port=9735
2018-12-02 21:24:37,503 INFO  fr.acinq.eclair.io.Peer  n:02911515d46e371eacb87dbd5f513b03ab23031d17c3668293a8cca5369072dbea - setting up gossipTimestampFilter=GossipTimestampFilter(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,1543778650,4294967295)
2018-12-02 21:24:38,922 INFO  f.acinq.eclair.io.Client  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - connecting to pubkey=03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf host=13.92.254.226 port=9735
2018-12-02 21:24:41,638 INFO  f.a.e.io.Authenticator  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - connection authenticated with 0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4@51.15.123.173:9735 direction=outgoing
2018-12-02 21:24:43,736 INFO  f.acinq.eclair.io.Client  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - connection failed to 03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf@13.92.254.226:9735
2018-12-02 21:24:45,630 INFO  fr.acinq.eclair.io.Peer  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - 0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 has features: initialRoutingSync=false channelRangeQueriesOptional=true channelRangeQueriesMandatory=false
2018-12-02 21:24:45,632 INFO  f.a.eclair.Diagnostics  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 c:2e83b1bf79dd86f33cf571ccabb2c9e4545ba2676fa4afd37c95ae5d64c04a3d - OUT msg=Error(2e83b1bf79dd86f33cf571ccabb2c9e4545ba2676fa4afd37c95ae5d64c04a3d,706c65617365207075626c69736820796f7572206c6f63616c20636f6d6d69746d656e74)
2018-12-02 21:24:45,632 INFO  f.a.eclair.router.Router  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - sending query_channel_range=QueryChannelRange(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,0,2147483647)
2018-12-02 21:24:45,632 INFO  f.a.eclair.router.Router  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - received query_channel_range=QueryChannelRange(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000,552151,4294415144)
2018-12-02 21:24:45,636 INFO  f.a.eclair.router.Router  n:0279c22ed7a068d10dc1a38ae66d2d6461e269226c60258c021b1ddcdfe4b00bc4 - sending back reply_channel_range with 306 items for range=(552151, 4294415144)
2018-12-02 21:24:50,928 INFO  f.acinq.eclair.io.Client  n:03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf - connecting to pubkey=03a9d79bcfab7feb0f24c3cd61a57f0f00de2225b6d31bce0bc4564efa3b1b5aaf host=13.92.254.226 port=9735

**Comment by sstone** [comment]
In the logs there are 2 different things:
- a synchronization issue with your peer, with returned a "sync error"
- your node is in WAIT_FOR_REMOTE_PUBLISH_FUTURE_COMMITMENT which means that its local state is behind what its peer knows i.e. it has lost data. 

Did you have a crash, a problem with your disks ? Are you using network drives  or a distributed file system ? Did you restore data from another system ?

There should be logs messages that would explain why your node fell behind. If your log file is too large or if you don't find the information you can contact us on [gitter](https://gitter.im/ACINQ/eclair) and we can work together and find out what happened.

**Comment by tukac** [comment]
It was running on dedicated local machine. Local ssd disk works fine. No system crash or Core 0.17.0.1 crash, or any other event occured. Log file may include events that were recorded after I have tried to restart it.

Some time before crash happened I had edited eclair.conf. I tried to rename my node to include special characters and encoded eclair.conf as UTF-8 text file. Could that be the reason?

full log file 20Mb
https://www.dropbox.com/s/nn2s0vh0kquobrb/eclair.log?dl=0

**Comment by sstone** [comment]
There a several sqlite errors, and then eclair becomes unable to load its channels:
```
2018-12-02 21:01:18,286 ERROR akka.io.TcpListener  - Bind failed for TCP channel on endpoint [/0.0.0.0:9735]java.net.BindException: Address already in use: bind
2018-12-02 21:01:21,580 ERROR f.a.e.gui.FxPreloader  - java.lang.RuntimeException: TCP bind failed
2018-12-02 21:01:51,778 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
2018-12-02 21:01:54,886 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
2018-12-02 21:01:57,948 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
2018-12-02 21:02:01,006 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
2018-12-02 21:02:10,685 ERROR f.a.e.channel.Channel  n:02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469 c:9a7719dc3e569a61822a7159d17ebaa69521c86574c1124c9a58d99c0bd68a10 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:02:31,445 ERROR a.a.OneForOneStrategy  - [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)org.sqlite.SQLiteException: [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)
2018-12-02 21:02:32,836 ERROR a.a.OneForOneStrategy  - [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)org.sqlite.SQLiteException: [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)
2018-12-02 21:02:43,421 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:02:49,043 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)
2018-12-02 21:02:50,433 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)
2018-12-02 21:02:51,974 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume org.sqlite.SQLiteException: [SQLITE_IOERR_ACCESS]  I/O error within the xAccess (disk I/O error)
2018-12-02 21:03:22,463 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:07:40,033 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:08:52,014 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:11:02,198 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:16:56,079 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:18:44,666 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:20:54,387 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:21:57,202 ERROR f.a.e.channel.Channel  n:02cdf83ef8e45908b1092125d25c68dcec7751ca8d39f557775cd842e5bc127469 c:9a7719dc3e569a61822a7159d17ebaa69521c86574c1124c9a58d99c0bd68a10 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:21:59,713 ERROR f.a.e.channel.Channel  n:0307243743f60637f090347f9f2c1c98017071fd8f6afd8d6f6f6a64c7393a858a c:d766912ef51d2eba74101fa66f4fadef0492c6e7efed382e13496a84e3bd9407 - peer sent error: ascii='sync error' bin=73796e63206572726f72
2018-12-02 21:25:23,059 ERROR f.a.e.gui.FxPreloader  - fr.acinq.eclair.IncompatibleDBException$: database is not compatible with this version of eclair
2018-12-02 21:25:25,334 ERROR f.a.e.gui.FxPreloader  - fr.acinq.eclair.IncompatibleDBException$: database is not compatible with this version of eclair
2018-12-02 21:27:08,951 ERROR f.a.e.gui.FxPreloader  - fr.acinq.eclair.IncompatibleDBException$: database is not compatible with this version of eclair
2018-12-02 21:42:23,422 ERROR f.a.e.gui.FxPreloader  - fr.acinq.eclair.IncompatibleDBException$: database is not compatible with this version of eclair
```

Was there some kind of maintenance on your node around 2018-12-02 21:01:18 ? 
There are also tcp binding errors which may indicate that several eclair instance were launched concurrently. Do you use specific tools to start or monitor your node ? Are you running multiple nodes with different parameters on the same machine ?

**Comment by tukac** [comment]
Arround that time I was setting up dedicated IP with my VPN provider. Eclair was running at the time. Machine is running providers client. All is very stable. Other than that plain vanilla node. Eclair is in Task Scheduler set up to start 10 min after boot.

Is there a way to restore?

**Comment by sstone** [comment]
Unfortunately I don't think there is an easy way. You can make a copy of your data directory, delete the network database and start again but it's a long shot since its very likely that your channel database has been corrupted and is unreadable. 
There are still a few things we could try, can you please contact me on [gitter](https://gitter.im/ACINQ/eclair) ?

**Comment by sstone** [comment]
Additional info: even if several instances of eclair were started with the same data dir and parameters it would not corrupt your eclair database. AFAIK could only cause problems when sqlite databases are stored on exotic file systems, network drives... but it's not the case here. Can you check windows logs for system errors around 2018-12-02 21:01:18 ? Can you also check if a copy of our `eclair.sqlite` database can be opened with `sqlbrowser` ?

**Comment by tukac** [comment]
Wimdows system logs:

Error	2.12.2018. 21:30:35	Microsoft-Windows-DistributedCOM	10010	None	The server Microsoft.Windows.ContentDeliveryManager_10.0.17134.1_neutral_neutral_cw5n1h2txyewy!App.AppXryc2qd338f5728r9gzzazav8206ba77s.mca did not register with DCOM within the required timeout.
Error	2.12.2018. 21:30:34	Microsoft-Windows-DistributedCOM	10010	None	The server Microsoft.Windows.Cortana_1.10.7.17134_neutral_neutral_cw5n1h2txyewy!CortanaUI.AppXjytc7c0yvwb8n3cw0r82k4364sd1s7bv.mca did not register with DCOM within the required timeout.
Information	2.12.2018. 21:30:33	User32	1074	None	"The process C:\Windows\System32\RuntimeBroker.exe (DESKTOP-2ITHKJH) has initiated the restart of computer DESKTOP-2ITHKJH on behalf of user DESKTOP-2ITHKJH\User for the following reason: Other (Unplanned)
 Reason Code: 0x0
 Shutdown Type: restart
 Comment: "
Error	2.12.2018. 21:27:31	Microsoft-Windows-DistributedCOM	10016	None	"The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E09305837}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-A83993939}
 to the user DESKTOP-2ITHKJH\User SID (S-1-5-21-478392938-3330431229-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool."
Warning	2.12.2018. 21:20:33	Microsoft-Windows-DNS-Client	1014	(1014)	Name resolution for the name o-ring.msedge.net timed out after none of the configured DNS servers responded.
Warning	2.12.2018. 20:55:50	Microsoft-Windows-DNS-Client	1014	(1014)	Name resolution for the name cdn.onenote.net timed out after none of the configured DNS servers responded.
Warning	2.12.2018. 20:47:39	Microsoft-Windows-DNS-Client	1014	(1014)	Name resolution for the name disc601-prod.do.dsp.mp.microsoft.com timed out after none of the configured DNS servers responded.

I can open eclair.sqlite with DB browser for SQlite!

**Comment by sstone** [comment]
Ok this is good news! 
The simplest way to move forward would be to send me your eclair.sqlite db. It's not ideal from a privacy point of view (I will be able to tell who you opened a channel with, who you've paid ....) but I won't be able to access your private keys (which are generate from your seed.dat file which you should definitely not send me :)). I'll try and restore the db, send it back to you and it may help us understand what went wrong.

**Comment by tukac** [comment]
Ok lets do that. I'll send in gitter

**Comment by sstone** [comment]
The eclair database was corrupted. I was able to restore all channel data, except for one, and sent the restored db back to OP who got their channel back.
