### ISSUE TITLE
java.lang.RuntimeException: serialization error: alias: 

### ISSUE THREAD

**Issue by CatOkHero** [ACINQ/eclair#819]
Dear Eclair Team, 

I have the issue when Eclair was consuming 99% of CPU and crashed after 20-30 minutes of work. 
By logs, I have found that my eclair.node-alias was too big

Here is the crash log:
```
2019-01-13 13:00:07,591 INFO  fr.acinq.eclair.Setup  - version=0.2-beta8 commit=52821b8664c329cc2e14e237df1aeff96b5260d5
2019-01-13 13:00:07,689 INFO  o.b.Secp256k1Context  - couldn't find secp256k1 library, defaulting to spongycastle
2019-01-13 13:00:08,357 INFO  fr.acinq.eclair.Setup  - nodeid=022706ea6499a904b0a545fa6212455bb3fbd0b608e901e3e652a85219b2ed0fd8 alias=”BitcoinLightningNodeUkraine”
2019-01-13 13:00:08,358 INFO  fr.acinq.eclair.Setup  - using chain=mainnet chainHash=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000
2019-01-13 13:00:08,359 INFO  fr.acinq.eclair.Setup  - initializing secure random generator
2019-01-13 13:00:11,627 INFO  fr.acinq.eclair.Setup  - current feeratesPerKB=FeeratesPerKB(7537,2585,2000,2000,2000,2000) feeratesPerKw=FeeratesPerKw(1884,646,500,500,500,500)
2019-01-13 13:00:11,688 INFO  f.a.eclair.router.Router  - loading network announcements from db...
2019-01-13 13:00:11,693 INFO  f.a.eclair.router.Router  - loaded from db: channels=0 nodes=0 updates=0
2019-01-13 13:00:11,693 INFO  f.acinq.eclair.io.Server  - bound on /0:0:0:0:0:0:0:0:9735
2019-01-13 13:00:11,740 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume akka.actor.ActorInitializationException: akka://eclair-node-gui/user/$h/router: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: serialization error: alias: [”BitcoinLightningNodeUkraine”] requires 264 bits but field is fixed size of 256 bits
	at fr.acinq.eclair.package$.serializationResult(package.scala:53)
	at fr.acinq.eclair.router.Announcements$.nodeAnnouncementWitnessEncode(Announcements.scala:40)
	at fr.acinq.eclair.router.Announcements$.makeNodeAnnouncement(Announcements.scala:81)
	at fr.acinq.eclair.router.Router.<init>(Router.scala:143)
	at fr.acinq.eclair.router.Router$$anonfun$props$1.apply(Router.scala:694)
	at fr.acinq.eclair.router.Router$$anonfun$props$1.apply(Router.scala:694)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 common frames omitted

2019-01-13 13:00:11,741 ERROR akka.actor.ActorCell  - changing Resume into Create after akka.actor.ActorInitializationException: akka://eclair-node-gui/user/$h/router: exception during creation
2019-01-13 13:00:11,741 INFO  f.a.eclair.router.Router  - loading network announcements from db...
2019-01-13 13:00:11,742 INFO  f.a.eclair.router.Router  - loaded from db: channels=0 nodes=0 updates=0
2019-01-13 13:00:11,742 INFO  f.a.e.b.b.zmq.ZMQActor  - connected to tcp://127.0.0.1:29000
2019-01-13 13:00:11,745 INFO  fr.acinq.eclair.Setup  - json-rpc api is disabled
2019-01-13 13:00:11,748 ERROR f.a.e.SimpleSupervisor  - supervisor caught error for child=router strategy=Resume akka.actor.ActorInitializationException: akka://eclair-node-gui/user/$h/router: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:180)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:374)
	at akka.actor.dungeon.FaultHandling$class.faultResume(FaultHandling.scala:102)
	at akka.actor.ActorCell.faultResume(ActorCell.scala:374)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:466)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: serialization error: alias: [”BitcoinLightningNodeUkraine”] requires 264 bits but field is fixed size of 256 bits
	at fr.acinq.eclair.package$.serializationResult(package.scala:53)
	at fr.acinq.eclair.router.Announcements$.nodeAnnouncementWitnessEncode(Announcements.scala:40)
	at fr.acinq.eclair.router.Announcements$.makeNodeAnnouncement(Announcements.scala:81)
	at fr.acinq.eclair.router.Router.<init>(Router.scala:143)
	at fr.acinq.eclair.router.Router$$anonfun$props$1.apply(Router.scala:694)
	at fr.acinq.eclair.router.Router$$anonfun$props$1.apply(Router.scala:694)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	at akka.actor.dungeon.FaultHandling$class.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling$class.faultCreate(FaultHandling.scala:130)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:374)
	at akka.actor.dungeon.FaultHandling$class.faultResume(FaultHandling.scala:102)
	at akka.actor.ActorCell.faultResume(ActorCell.scala:374)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:466)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

Eclair stopped to working after the log reaches 9 gigs.
If you need, I can attach full log file

**Comment by sstone** [comment]
Can you please paste your `eclair.conf` file (just replace passwords with XXXX) ?

**Comment by CatOkHero** [comment]
eclair.chain=mainnet
eclair.bitcoind.rpcport=8332
eclair.bitcoind.rpcuser=XXXXX-XXXXX
eclair.bitcoind.rpcpassword=XXXXX
eclair.node-alias=вЂќUkraineNodeвЂќ
eclair.node-color=ff9900

**Comment by pm47** [comment]
Could that be the UTF8 encoding bug that @dpad85 discovered last week?

**Comment by CatOkHero** [comment]
With вЂќUkraineNodeвЂќ it actually works
the issue was when I named it "BitcoinLightningNodeUkraine"
I was also thinking about the encoding

The name of the computer is in English, so shouldn't be a problem with that

**Comment by araspitzu** [comment]
@CatOkHero if you upgrade to eclair Beta9 the issue should be fixed.
