### ISSUE TITLE
couldn't publish funding tx

### ISSUE THREAD

**Issue by 4stone** [ACINQ/eclair#874]
When I open channel to 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@34.250.234.192:9735 on Eclair，it always return this error.

How to fix it？pls give help. 3ks!

Eclair log：
2019-02-19 11:10:45,684 INFO  f.a.e.channel.Channel  n:03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 c:edd75f90c0769d1a41b4b6f2c588c9a99a92ae3b27451fedebcec8b87a651a8e - publishing funding tx for channelId=edd75f90c0769d1a41b4b6f2c588c9a99a92ae3b27451fedebcec8b87a651a8e fundingTxid=8f1a657ab8c8ceebed1f45273bae929aa9c988c5f2b6b4411a9d76c0905fd7ed
2019-02-19 11:10:45,696 INFO  f.a.e.channel.Channel  n:03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 c:edd75f90c0769d1a41b4b6f2c588c9a99a92ae3b27451fedebcec8b87a651a8e - committing txid=8f1a657ab8c8ceebed1f45273bae929aa9c988c5f2b6b4411a9d76c0905fd7ed
2019-02-19 11:10:45,769 WARN  f.a.e.b.b.BitcoinCoreWallet  - txid=8f1a657ab8c8ceebed1f45273bae929aa9c988c5f2b6b4411a9d76c0905fd7ed error=Error(-26,non-mandatory-script-verify-flag (Witness program hash mismatch) (code 64))
2019-02-19 11:10:45,773 INFO  f.a.eclair.gui.Handlers  - could not open channel java.lang.RuntimeException: couldn't publish funding tx
	at fr.acinq.eclair.channel.Channel$$anonfun$13$$anonfun$applyOrElse$19.apply(Channel.scala:417)
	at fr.acinq.eclair.channel.Channel$$anonfun$13$$anonfun$applyOrElse$19.apply(Channel.scala:411)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2019-02-19 11:10:45,773 ERROR f.a.e.channel.Channel  n:03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 c:edd75f90c0769d1a41b4b6f2c588c9a99a92ae3b27451fedebcec8b87a651a8e - failed to publish funding tx
2019-02-19 11:10:45,773 INFO  f.a.eclair.Diagnostics  n:03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 c:edd75f90c0769d1a41b4b6f2c588c9a99a92ae3b27451fedebcec8b87a651a8e - OUT msg=Error

Bitcoin Core version： v0.17.0.1 (64 bits)
bitcoin.conf：
testnet=1
server=1
rpcuser=btc
rpcpassword=btc
txindex=1
zmqpubrawblock=tcp://127.0.0.1:29000
zmqpubrawtx=tcp://127.0.0.1:29000
addresstype=p2sh-segwit
deprecatedrpc=signrawtransaction

Eclair version：v0.2-beta9
eclair.conf：
eclair.chain=testnet
eclair.bitcoind.rpcuser=btc
eclair.bitcoind.rpcpassword=btc
eclair.node-alias=eclair
eclair.node-color=49daaa
eclair.api.enabled=true
eclair.api.password="eclairtest"
eclair.bitcoind.zmqblock="tcp://127.0.0.1:29000"
eclair.bitcoind.zmqtx="tcp://127.0.0.1:29000"

**Comment by 4stone** [comment]
[eclair.log](https://github.com/ACINQ/eclair/files/2879369/eclair.log)

**Comment by 4stone** [comment]
D:\Bitcoin\testnet3\debug.log

2019-02-19T12:59:20Z 




2019-02-19T12:59:20Z Bitcoin Core version v0.17.0.1 (release build)
2019-02-19T12:59:20Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2019-02-19T12:59:21Z Assuming ancestors of block 0000000000000037a8cd3e06cd5edbfe9dd1dbcc5dacab279376ef7cfc2b4c75 have valid signatures.
2019-02-19T12:59:21Z Setting nMinimumChainWork=00000000000000000000000000000000000000000000007dbe94253893cbd463
2019-02-19T12:59:21Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2019-02-19T12:59:21Z Using RdRand as an additional entropy source
2019-02-19T12:59:21Z GUI: "registerShutdownBlockReason: Successfully registered: Bitcoin Core 尚未安全退出"
2019-02-19T12:59:21Z Default data directory C:\Users\Administrator\AppData\Roaming\Bitcoin
2019-02-19T12:59:21Z Using data directory D:\Bitcoin\testnet3
2019-02-19T12:59:21Z Using config file D:\Bitcoin\bitcoin.conf
2019-02-19T12:59:21Z Using at most 125 automatic connections (2048 file descriptors available)
2019-02-19T12:59:21Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2019-02-19T12:59:21Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2019-02-19T12:59:21Z Using 4 threads for script verification
2019-02-19T12:59:21Z scheduler thread start
2019-02-19T12:59:21Z libevent: getaddrinfo: nodename nor servname provided, or not known
2019-02-19T12:59:21Z Binding RPC on address ::1 port 18332 failed.
2019-02-19T12:59:21Z HTTP: creating work queue of depth 16
2019-02-19T12:59:21Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
2019-02-19T12:59:21Z HTTP: starting 4 worker threads
2019-02-19T12:59:21Z Using wallet directory D:\Bitcoin\testnet3\wallets
2019-02-19T12:59:21Z init message: 正在检测钱包的完整性...
2019-02-19T12:59:21Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2019-02-19T12:59:21Z Using wallet wallet.dat
2019-02-19T12:59:21Z BerkeleyEnvironment::Open: LogDir=D:\Bitcoin\testnet3\wallets\database ErrorFile=D:\Bitcoin\testnet3\wallets\db.log
2019-02-19T12:59:21Z Cache configuration:
2019-02-19T12:59:21Z * Using 2.0MiB for block index database
2019-02-19T12:59:21Z * Using 56.0MiB for transaction index database
2019-02-19T12:59:21Z * Using 8.0MiB for chain state database
2019-02-19T12:59:21Z * Using 384.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2019-02-19T12:59:21Z init message: 正在加载区块索引...
2019-02-19T12:59:21Z Opening LevelDB in D:\Bitcoin\testnet3\blocks\index
2019-02-19T12:59:21Z Opened LevelDB successfully
2019-02-19T12:59:21Z Using obfuscation key for D:\Bitcoin\testnet3\blocks\index: 0000000000000000
2019-02-19T12:59:30Z LoadBlockIndexDB: last block file = 156
2019-02-19T12:59:30Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=25303, size=133630629, heights=1453003...1478270, time=2019-01-18...2019-02-19)
2019-02-19T12:59:30Z Checking all blk files are present...
2019-02-19T12:59:31Z Opening LevelDB in D:\Bitcoin\testnet3\chainstate
2019-02-19T12:59:31Z Opened LevelDB successfully
2019-02-19T12:59:31Z Using obfuscation key for D:\Bitcoin\testnet3\chainstate: f5f371064d1b878c
2019-02-19T12:59:31Z Loaded best chain: hashBestChain=00000000000007db242d40a32953f14b5172177c5b183d4a1795bda5757d2ee1 height=1478270 date=2019-02-19T12:55:07Z progress=0.999997
2019-02-19T12:59:31Z init message: 回退区块
2019-02-19T12:59:38Z init message: 正在验证区块...
2019-02-19T12:59:38Z Verifying last 6 blocks at level 3
2019-02-19T12:59:38Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2019-02-19T12:59:38Z No coin database inconsistencies in last 6 blocks (56 transactions)
2019-02-19T12:59:38Z  block index           17102ms
2019-02-19T12:59:38Z Opening LevelDB in D:\Bitcoin\testnet3\indexes\txindex
2019-02-19T12:59:38Z Opened LevelDB successfully
2019-02-19T12:59:38Z Using obfuscation key for D:\Bitcoin\testnet3\indexes\txindex: 0000000000000000
2019-02-19T12:59:38Z init message: 正在加载钱包...
2019-02-19T12:59:38Z txindex thread start
2019-02-19T12:59:38Z Syncing txindex with block chain from height 1478269
2019-02-19T12:59:38Z [default wallet] nFileVersion = 170001
2019-02-19T12:59:38Z [default wallet] Keys: 0 plaintext, 4042 encrypted, 4042 w/ metadata, 4042 total. Unknown wallet records: 1
2019-02-19T12:59:38Z [default wallet] Wallet completed loading in              70ms
2019-02-19T12:59:38Z [default wallet] setKeyPool.size() = 1959
2019-02-19T12:59:38Z [default wallet] mapWallet.size() = 53
2019-02-19T12:59:38Z [default wallet] mapAddressBook.size() = 63
2019-02-19T12:59:38Z txindex is enabled at height 1478270
2019-02-19T12:59:38Z mapBlockIndex.size() = 1478542
2019-02-19T12:59:38Z txindex thread exit
2019-02-19T12:59:38Z nBestHeight = 1478270
2019-02-19T12:59:38Z torcontrol thread start
2019-02-19T12:59:38Z init message: 正在加载P2P地址...
2019-02-19T12:59:38Z Leaving InitialBlockDownload (latching to false)
2019-02-19T12:59:38Z Imported mempool transactions from disk: 6 succeeded, 0 failed, 0 expired, 0 already there
2019-02-19T12:59:38Z Loaded 33475 addresses from peers.dat  106ms
2019-02-19T12:59:38Z init message: 正在加载黑名单...
2019-02-19T12:59:38Z init message: 正在启动网络线程...
2019-02-19T12:59:38Z init message: 加载完成
2019-02-19T12:59:38Z net thread start
2019-02-19T12:59:38Z addcon thread start
2019-02-19T12:59:38Z opencon thread start
2019-02-19T12:59:38Z dnsseed thread start
2019-02-19T12:59:38Z msghand thread start
2019-02-19T12:59:38Z GUI: Platform customization: "windows"
2019-02-19T12:59:38Z GUI: PaymentServer::LoadRootCAs: Loaded  23  root certificates
2019-02-19T12:59:45Z New outbound peer connected: version: 70015, blocks=1414448, peer=0
2019-02-19T12:59:49Z Loading addresses from DNS seeds (could take a while)
2019-02-19T12:59:50Z 67 addresses found from DNS seeds
2019-02-19T12:59:50Z dnsseed thread exit
2019-02-19T12:59:51Z New outbound peer connected: version: 70015, blocks=1478276, peer=1
2019-02-19T12:59:57Z UpdateTip: new best=000000000000033de95818a0efc4156da375cd3cdd8e0444a642ba93e6edf59c height=1478271 version=0x2cde2000 log2_work=71.936044 tx=48896583 date='2019-02-19T12:55:30Z' progress=0.999997 cache=0.0MiB(16txo) warning='最后100个区块中的58个包含未知的版本号'
2019-02-19T12:59:57Z UpdateTip: new best=0000000000000c5cc39d71cfc0590a6a4c2a321bcda084e7567fb8fe9fadc1a6 height=1478272 version=0x20000000 log2_work=71.936046 tx=48896585 date='2019-02-19T12:55:56Z' progress=0.999997 cache=0.0MiB(20txo) warning='最后100个区块中的58个包含未知的版本号'
2019-02-19T12:59:57Z UpdateTip: new best=0000000000000f94e0fe12699234acb8dd04319d993312f7524e7ef31d658eb9 height=1478273 version=0x20000000 log2_work=71.936047 tx=48896592 date='2019-02-19T12:56:12Z' progress=0.999997 cache=0.0MiB(35txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T12:59:57Z UpdateTip: new best=00000000000009d2beb0cc523e2873ab33697926873cff460b1c0cc6981bfc4b height=1478274 version=0x3c05a000 log2_work=71.936049 tx=48896597 date='2019-02-19T12:56:21Z' progress=0.999997 cache=0.0MiB(46txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T12:59:57Z UpdateTip: new best=0000000000000fb43542b3d45330fe93883056528d65846e48f4739ea66f0eb3 height=1478275 version=0x20000000 log2_work=71.93605 tx=48896601 date='2019-02-19T12:57:04Z' progress=0.999998 cache=0.0MiB(58txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T12:59:57Z UpdateTip: new best=00000000000009c442bf95ab62e9288fa211770281845294d5a31e2c263ed911 height=1478276 version=0x20000000 log2_work=71.936051 tx=48896622 date='2019-02-19T12:59:07Z' progress=0.999999 cache=0.0MiB(110txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T12:59:57Z New outbound peer connected: version: 70015, blocks=1478276, peer=2
2019-02-19T12:59:58Z New outbound peer connected: version: 70015, blocks=1478276, peer=3
2019-02-19T13:00:05Z New outbound peer connected: version: 70015, blocks=1478276, peer=4
2019-02-19T13:00:38Z New outbound peer connected: version: 70015, blocks=1414448, peer=5
2019-02-19T13:00:39Z New outbound peer connected: version: 70015, blocks=1478276, peer=6
2019-02-19T13:00:46Z New outbound peer connected: version: 70015, blocks=1478276, peer=7
2019-02-19T13:02:51Z UpdateTip: new best=0000000000000f9cd898ae390030f4afc0670a6084f512de1bac5a7689fa1e01 height=1478277 version=0x3dcea000 log2_work=71.936053 tx=48896652 date='2019-02-19T13:02:26Z' progress=1.000000 cache=0.0MiB(184txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T13:03:59Z UpdateTip: new best=0000000000000d2cf15a3e049494438aee935fd275ea6dc62dcd0f85f5016acd height=1478278 version=0x20000000 log2_work=71.936054 tx=48896678 date='2019-02-19T13:04:02Z' progress=1.000000 cache=0.0MiB(209txo) warning='最后100个区块中的56个包含未知的版本号'
2019-02-19T13:04:11Z UpdateTip: new best=00000000000006c4dbb98d72a245738ce9f976f95f0fadba78e982f1c2651f92 height=1478279 version=0x20000000 log2_work=71.936056 tx=48896681 date='2019-02-19T13:03:59Z' progress=1.000000 cache=0.0MiB(215txo) warning='最后100个区块中的56个包含未知的版本号'
2019-02-19T13:04:53Z UpdateTip: new best=0000000000000d05c2161336fe56271fe10bb2d7a9c04015683e63c61a5870d0 height=1478280 version=0x6ed38000 log2_work=71.936057 tx=48896685 date='2019-02-19T13:04:12Z' progress=0.999999 cache=0.0MiB(220txo) warning='最后100个区块中的56个包含未知的版本号'
2019-02-19T13:06:40Z UpdateTip: new best=00000000000000f69aa7d77c349fe94740e02e2839721da92257354d2a2ae703 height=1478281 version=0x2b974000 log2_work=71.936059 tx=48896699 date='2019-02-19T13:06:34Z' progress=1.000000 cache=0.0MiB(249txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T13:07:06Z UpdateTip: new best=0000000000000b96aebc77456f766451739a39d5a343967228a37e7e6126eb74 height=1478282 version=0x3a4d4000 log2_work=71.93606 tx=48896702 date='2019-02-19T13:06:40Z' progress=1.000000 cache=0.0MiB(254txo) warning='最后100个区块中的58个包含未知的版本号'
2019-02-19T13:07:33Z [default wallet] keypool reserve 2063
2019-02-19T13:07:33Z [default wallet] keypool keep 2063
2019-02-19T13:07:47Z UpdateTip: new best=0000000000000c743182ea1c85870277b077354c6208a76d0bcbd351c5452ab8 height=1478283 version=0x20000000 log2_work=71.936062 tx=48896707 date='2019-02-19T13:07:50Z' progress=1.000000 cache=0.2MiB(862txo) warning='最后100个区块中的58个包含未知的版本号'
2019-02-19T13:08:35Z [default wallet] keypool reserve 2064
2019-02-19T13:08:35Z [default wallet] keypool keep 2064
2019-02-19T13:08:36Z [default wallet] keypool reserve 3020
2019-02-19T13:08:36Z [default wallet] Fee Calculation: Fee:2348 Bytes:1174 Needed:2348 Tgt:0 (requested 0) Reason:"PayTxFee set" Decay 0.00000: Estimation: (-1 - -1) nan% 0.0/(0.0 0 mem 0.0 out) Fail: (-1 - -1) nan% 0.0/(0.0 0 mem 0.0 out)
2019-02-19T13:08:36Z [default wallet] keypool keep 3020
2019-02-19T13:09:15Z UpdateTip: new best=00000000000009cf82ee31b949b8487c301df57177692173add479bbf74e7385 height=1478284 version=0x3fffe000 log2_work=71.936063 tx=48896731 date='2019-02-19T13:09:41Z' progress=1.000000 cache=1.1MiB(6015txo) warning='最后100个区块中的58个包含未知的版本号'
2019-02-19T13:09:20Z UpdateTip: new best=0000000000000ebdce99b749823785b7bf51902696f2ecc030135b3cc803fa3d height=1478285 version=0x20000000 log2_work=71.936065 tx=48896732 date='2019-02-19T13:09:15Z' progress=1.000000 cache=1.1MiB(6018txo) warning='最后100个区块中的57个包含未知的版本号'
2019-02-19T13:09:31Z GUI:   OpenType support missing for "SimSun", script 11
2019-02-19T13:09:31Z GUI:   OpenType support missing for "Arial", script 11
2019-02-19T13:09:31Z GUI:   OpenType support missing for "PMingLiU", script 11
2019-02-19T13:09:31Z GUI:   OpenType support missing for "Gulim", script 11
2019-02-19T13:09:31Z GUI:   OpenType support missing for "MS UI Gothic", script 11
2019-02-19T13:09:31Z GUI:   OpenType support missing for "SimSun", script 16
2019-02-19T13:09:31Z GUI:   OpenType support missing for "Arial", script 16
2019-02-19T13:09:31Z GUI:   OpenType support missing for "PMingLiU", script 16
2019-02-19T13:09:31Z GUI:   OpenType support missing for "Gulim", script 16
2019-02-19T13:09:31Z GUI:   OpenType support missing for "MS UI Gothic", script 16

**Comment by 4stone** [comment]
I change my bitcoin core version to Bitcoin Core  v0.17.1 (64 bits).
Then I open channel on Eclair，I get another error: Error: Please enter the wallet passphrase with walletpassphrase first. (code: -13).
I cannot find where and how to enter walletpassphrase，because it havenot given attention.

**Comment by 4stone** [comment]
I use cmd “walletpassphrase "my pass phrase" 100000000” on bitcoin core console， and create channel success. Thanks your help :)
